package gov.bnm.rh.views;

import gov.bnm.rh.entities.CategoriesImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 29 14:10:08 SGT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CategoriesViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CategoryID {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getCategoryID();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setCategoryID((BigDecimal)value);
            }
        }
        ,
        CategoryName {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getCategoryName();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setCategoryName((String)value);
            }
        }
        ,
        CategoryDescription {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getCategoryDescription();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setCategoryDescription((String)value);
            }
        }
        ,
        ParentNodeID {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getParentNodeID();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setParentNodeID((BigDecimal)value);
            }
        }
        ,
        CreatedDate {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setCreatedDate((Timestamp)value);
            }
        }
        ,
        LastUpdated {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getLastUpdated();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setLastUpdated((Timestamp)value);
            }
        }
        ,
        EntryID {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getEntryID();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setEntryID((Integer)value);
            }
        }
        ,
        isActive {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getisActive();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setisActive((Boolean)value);
            }
        }
        ,
        isAllowToPublish {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getisAllowToPublish();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setisAllowToPublish((Boolean)value);
            }
        }
        ,
        PolicyCount {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getPolicyCount();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setPolicyCount((Integer)value);
            }
        }
        ,
        isCheckCategory {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getisCheckCategory();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setisCheckCategory((Boolean)value);
            }
        }
        ,
        PolicysectorcategoryView {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getPolicysectorcategoryView();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PolicycategoriespartitionView {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getPolicycategoriespartitionView();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CategoryParentLevelViewObj {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getCategoryParentLevelViewObj();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CategoriesCount {
            public Object get(CategoriesViewRowImpl obj) {
                return obj.getCategoriesCount();
            }

            public void put(CategoriesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(CategoriesViewRowImpl object);

        public abstract void put(CategoriesViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CATEGORYID = AttributesEnum.CategoryID.index();
    public static final int CATEGORYNAME = AttributesEnum.CategoryName.index();
    public static final int CATEGORYDESCRIPTION = AttributesEnum.CategoryDescription.index();
    public static final int PARENTNODEID = AttributesEnum.ParentNodeID.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATED = AttributesEnum.LastUpdated.index();
    public static final int ENTRYID = AttributesEnum.EntryID.index();
    public static final int ISACTIVE = AttributesEnum.isActive.index();
    public static final int ISALLOWTOPUBLISH = AttributesEnum.isAllowToPublish.index();
    public static final int POLICYCOUNT = AttributesEnum.PolicyCount.index();
    public static final int ISCHECKCATEGORY = AttributesEnum.isCheckCategory.index();
    public static final int POLICYSECTORCATEGORYVIEW = AttributesEnum.PolicysectorcategoryView.index();
    public static final int POLICYCATEGORIESPARTITIONVIEW = AttributesEnum.PolicycategoriespartitionView.index();
    public static final int CATEGORYPARENTLEVELVIEWOBJ = AttributesEnum.CategoryParentLevelViewObj.index();
    public static final int CATEGORIESCOUNT = AttributesEnum.CategoriesCount.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CategoriesViewRowImpl() {
    }

    /**
     * Gets Categories entity object.
     * @return the Categories
     */
    public CategoriesImpl getCategories() {
        return (CategoriesImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for CategoryID using the alias name CategoryID.
     * @return the CategoryID
     */
    public BigDecimal getCategoryID() {
        return (BigDecimal)getAttributeInternal(CATEGORYID);
    }

    /**
     * Sets <code>value</code> as attribute value for CategoryID using the alias name CategoryID.
     * @param value value to set the CategoryID
     */
    public void setCategoryID(BigDecimal value) {
        setAttributeInternal(CATEGORYID, value);
    }

    /**
     * Gets the attribute value for CategoryName using the alias name CategoryName.
     * @return the CategoryName
     */
    public String getCategoryName() {
        return (String)getAttributeInternal(CATEGORYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CategoryName using the alias name CategoryName.
     * @param value value to set the CategoryName
     */
    public void setCategoryName(String value) {
        setAttributeInternal(CATEGORYNAME, value);
    }

    /**
     * Gets the attribute value for CategoryDescription using the alias name CategoryDescription.
     * @return the CategoryDescription
     */
    public String getCategoryDescription() {
        return (String)getAttributeInternal(CATEGORYDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for CategoryDescription using the alias name CategoryDescription.
     * @param value value to set the CategoryDescription
     */
    public void setCategoryDescription(String value) {
        setAttributeInternal(CATEGORYDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ParentNodeID using the alias name ParentNodeID.
     * @return the ParentNodeID
     */
    public BigDecimal getParentNodeID() {
        return (BigDecimal)getAttributeInternal(PARENTNODEID);
    }

    /**
     * Sets <code>value</code> as attribute value for ParentNodeID using the alias name ParentNodeID.
     * @param value value to set the ParentNodeID
     */
    public void setParentNodeID(BigDecimal value) {
        setAttributeInternal(PARENTNODEID, value);
    }

    /**
     * Gets the attribute value for CreatedDate using the alias name CreatedDate.
     * @return the CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CreatedDate using the alias name CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdated using the alias name LastUpdated.
     * @return the LastUpdated
     */
    public Timestamp getLastUpdated() {
        return (Timestamp)getAttributeInternal(LASTUPDATED);
    }

    /**
     * Sets <code>value</code> as attribute value for LastUpdated using the alias name LastUpdated.
     * @param value value to set the LastUpdated
     */
    public void setLastUpdated(Timestamp value) {
        setAttributeInternal(LASTUPDATED, value);
    }

    /**
     * Gets the attribute value for EntryID using the alias name EntryID.
     * @return the EntryID
     */
    public Integer getEntryID() {
        return (Integer)getAttributeInternal(ENTRYID);
    }

    /**
     * Sets <code>value</code> as attribute value for EntryID using the alias name EntryID.
     * @param value value to set the EntryID
     */
    public void setEntryID(Integer value) {
        setAttributeInternal(ENTRYID, value);
    }

    /**
     * Gets the attribute value for isActive using the alias name isActive.
     * @return the isActive
     */
    public Boolean getisActive() {
        return (Boolean)getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for isActive using the alias name isActive.
     * @param value value to set the isActive
     */
    public void setisActive(Boolean value) {
        setAttributeInternal(ISACTIVE, value);
    }


    /**
     * Gets the attribute value for the calculated attribute isAllowToPublish.
     * @return the isAllowToPublish
     */
    public Boolean getisAllowToPublish() {
        return (Boolean) getAttributeInternal(ISALLOWTOPUBLISH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute isAllowToPublish.
     * @param value value to set the  isAllowToPublish
     */
    public void setisAllowToPublish(Boolean value) {
        setAttributeInternal(ISALLOWTOPUBLISH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PolicyCount.
     * @return the PolicyCount
     */
    public Integer getPolicyCount() {
        return (Integer) getAttributeInternal(POLICYCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PolicyCount.
     * @param value value to set the  PolicyCount
     */
    public void setPolicyCount(Integer value) {
        setAttributeInternal(POLICYCOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute isCheckCategory.
     * @return the isCheckCategory
     */
    public Boolean getisCheckCategory() {
        return (Boolean) getAttributeInternal(ISCHECKCATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute isCheckCategory.
     * @param value value to set the  isCheckCategory
     */
    public void setisCheckCategory(Boolean value) {
        setAttributeInternal(ISCHECKCATEGORY, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PolicysectorcategoryView.
     */
    public RowIterator getPolicysectorcategoryView() {
        return (RowIterator)getAttributeInternal(POLICYSECTORCATEGORYVIEW);
    }


  /**
   * Gets the associated <code>RowIterator</code> using master-detail link PolicycategoriespartitionView.
   */
    public RowIterator getPolicycategoriespartitionView() {
        return (RowIterator)getAttributeInternal(POLICYCATEGORIESPARTITIONVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CategoryParentLevelViewObj.
     */
    public RowIterator getCategoryParentLevelViewObj() {
        return (RowIterator)getAttributeInternal(CATEGORYPARENTLEVELVIEWOBJ);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CategoriesCount.
     */
    public RowIterator getCategoriesCount() {
        return (RowIterator)getAttributeInternal(CATEGORIESCOUNT);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
