package gov.bnm.rh.views;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 21 03:52:26 GMT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PolicycategoriespartitionViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CategoryID {
            public Object get(PolicycategoriespartitionViewRowImpl obj) {
                return obj.getCategoryID();
            }

            public void put(PolicycategoriespartitionViewRowImpl obj,
                            Object value) {
                obj.setCategoryID((BigDecimal)value);
            }
        },
        itemId {
            public Object get(PolicycategoriespartitionViewRowImpl obj) {
                return obj.getitemId();
            }

            public void put(PolicycategoriespartitionViewRowImpl obj,
                            Object value) {
                obj.setitemId((String)value);
            }
        },
        CategoryName {
            public Object get(PolicycategoriespartitionViewRowImpl obj) {
                return obj.getCategoryName();
            }

            public void put(PolicycategoriespartitionViewRowImpl obj,
                            Object value) {
                obj.setCategoryName((String)value);
            }
        },
        CategoriesView {
            public Object get(PolicycategoriespartitionViewRowImpl obj) {
                return obj.getCategoriesView();
            }

            public void put(PolicycategoriespartitionViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        PolicycategoriespartitionCountView {
            public Object get(PolicycategoriespartitionViewRowImpl obj) {
                return obj.getPolicycategoriespartitionCountView();
            }

            public void put(PolicycategoriespartitionViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PolicycategoriespartitionViewRowImpl object);

        public abstract void put(PolicycategoriespartitionViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CATEGORYID = AttributesEnum.CategoryID.index();
    public static final int ITEMID = AttributesEnum.itemId.index();
    public static final int CATEGORYNAME = AttributesEnum.CategoryName.index();
    public static final int CATEGORIESVIEW =
        AttributesEnum.CategoriesView.index();
    public static final int POLICYCATEGORIESPARTITIONCOUNTVIEW =
        AttributesEnum.PolicycategoriespartitionCountView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PolicycategoriespartitionViewRowImpl() {
    }

    /**
     * Gets Policycategoriespartition entity object.
     * @return the Policycategoriespartition
     */
    public EntityImpl getPolicycategoriespartition() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for CategoryID using the alias name CategoryID.
     * @return the CategoryID
     */
    public BigDecimal getCategoryID() {
        return (BigDecimal)getAttributeInternal(CATEGORYID);
    }

    /**
     * Sets <code>value</code> as attribute value for CategoryID using the alias name CategoryID.
     * @param value value to set the CategoryID
     */
    public void setCategoryID(BigDecimal value) {
        setAttributeInternal(CATEGORYID, value);
    }

    /**
     * Gets the attribute value for itemId using the alias name itemId.
     * @return the itemId
     */
    public String getitemId() {
        return (String)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for itemId using the alias name itemId.
     * @param value value to set the itemId
     */
    public void setitemId(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryName.
     * @return the CategoryName
     */
    public String getCategoryName() {
        return (String)getAttributeInternal(CATEGORYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CategoryName.
     * @param value value to set the  CategoryName
     */
    public void setCategoryName(String value) {
        setAttributeInternal(CATEGORYNAME, value);
    }


    /**
     * Gets the associated <code>Row</code> using master-detail link CategoriesView.
     */
    public Row getCategoriesView() {
        return (Row)getAttributeInternal(CATEGORIESVIEW);
    }

    /**
     * Sets the master-detail link CategoriesView between this object and <code>value</code>.
     */
    public void setCategoriesView(Row value) {
        setAttributeInternal(CATEGORIESVIEW, value);
    }


    /**
     * Gets the associated <code>Row</code> using master-detail link PolicycategoriespartitionCountView.
     */
    public Row getPolicycategoriespartitionCountView() {
        return (Row)getAttributeInternal(POLICYCATEGORIESPARTITIONCOUNTVIEW);
    }

    /**
     * Sets the master-detail link PolicycategoriespartitionCountView between this object and <code>value</code>.
     */
    public void setPolicycategoriespartitionCountView(Row value) {
        setAttributeInternal(POLICYCATEGORIESPARTITIONCOUNTVIEW, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
