package gov.bnm.rh.views;

import java.math.BigDecimal;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 21 19:48:40 SGT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InstitutionTypeSectorViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        INSTTYPEID {
            public Object get(InstitutionTypeSectorViewRowImpl obj) {
                return obj.getINSTTYPEID();
            }

            public void put(InstitutionTypeSectorViewRowImpl obj,
                            Object value) {
                obj.setINSTTYPEID((String)value);
            }
        }
        ,
        SectorID {
            public Object get(InstitutionTypeSectorViewRowImpl obj) {
                return obj.getSectorID();
            }

            public void put(InstitutionTypeSectorViewRowImpl obj,
                            Object value) {
                obj.setSectorID((BigDecimal)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(InstitutionTypeSectorViewRowImpl object);

        public abstract void put(InstitutionTypeSectorViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int INSTTYPEID = AttributesEnum.INSTTYPEID.index();
    public static final int SECTORID = AttributesEnum.SectorID.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InstitutionTypeSectorViewRowImpl() {
    }

    /**
     * Gets InstitutionTypeSector entity object.
     * @return the InstitutionTypeSector
     */
    public EntityImpl getInstitutionTypeSector() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for INSTTYPEID using the alias name INSTTYPEID.
     * @return the INSTTYPEID
     */
    public String getINSTTYPEID() {
        return (String) getAttributeInternal(INSTTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for INSTTYPEID using the alias name INSTTYPEID.
     * @param value value to set the INSTTYPEID
     */
    public void setINSTTYPEID(String value) {
        setAttributeInternal(INSTTYPEID, value);
    }

    /**
     * Gets the attribute value for SectorID using the alias name SectorID.
     * @return the SectorID
     */
    public BigDecimal getSectorID() {
        return (BigDecimal) getAttributeInternal(SECTORID);
    }

    /**
     * Sets <code>value</code> as attribute value for SectorID using the alias name SectorID.
     * @param value value to set the SectorID
     */
    public void setSectorID(BigDecimal value) {
        setAttributeInternal(SECTORID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
