package gov.bnm.rh.views;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 09 04:17:16 GMT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InternaluserViewRowImpl extends ViewRowImpl {
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum {
    ID {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getID();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setID((String)value);
      }
    }
    ,
    USERID {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getUSERID();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setUSERID((String)value);
      }
    }
    ,
    FULLNAME {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getFULLNAME();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setFULLNAME((String)value);
      }
    }
    ,
    STATUS {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getSTATUS();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setSTATUS((String)value);
      }
    }
    ,
    PRIMARYROLE {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getPRIMARYROLE();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setPRIMARYROLE((String)value);
      }
    }
    ,
    EMAIL {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getEMAIL();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setEMAIL((String)value);
      }
    }
    ,
    PASSWORD {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getPASSWORD();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setPASSWORD((String)value);
      }
    }
    ,
    DESIGNATION {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getDESIGNATION();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setDESIGNATION((String)value);
      }
    }
    ,
    DEPTID {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getDEPTID();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setDEPTID((String)value);
      }
    }
    ,
    ACCLASTUPDATE {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getACCLASTUPDATE();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setACCLASTUPDATE((Timestamp)value);
      }
    }
    ,
    APPROVERID {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getAPPROVERID();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setAPPROVERID((String)value);
      }
    }
    ,
    IDENTITYNO {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getIDENTITYNO();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setIDENTITYNO((String)value);
      }
    }
    ,
    PASSPORTNO {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getPASSPORTNO();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setPASSPORTNO((String)value);
      }
    }
    ,
    TELEPHONE {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getTELEPHONE();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setTELEPHONE((String)value);
      }
    }
    ,
    MOBILE {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getMOBILE();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setMOBILE((String)value);
      }
    }
    ,
    FAX {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getFAX();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setFAX((String)value);
      }
    }
    ,
    RANK {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getRANK();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setRANK((Integer)value);
      }
    }
    ,
    PRIMARYSYSNAME {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getPRIMARYSYSNAME();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setPRIMARYSYSNAME((String)value);
      }
    }
    ,
    EXTERNALACCESS {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getEXTERNALACCESS();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setEXTERNALACCESS((String)value);
      }
    }
    ,
    PORTALSTATUS {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getPORTALSTATUS();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setPORTALSTATUS((String)value);
      }
    }
    ,
    LASTLOGINTIME {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getLASTLOGINTIME();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setLASTLOGINTIME((Timestamp)value);
      }
    }
    ,
    SYSTEM {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getSYSTEM();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setSYSTEM((String)value);
      }
    }
    ,
    DepName {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getDepName();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setDepName((String)value);
      }
    }
    ,
    InternaluserUsergroupView {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getInternaluserUsergroupView();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    PolicybnmuserspartitionView {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getPolicybnmuserspartitionView();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    RequestlistView {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getRequestlistView();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    DepartmentView {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getDepartmentView();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    EnquiryfaqForEnqPendingViewObj {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getEnquiryfaqForEnqPendingViewObj();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    EnquiryfaqForEnqViewObj {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getEnquiryfaqForEnqViewObj();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    EnquiryfaqForEnqViewObj1 {
      public Object get(InternaluserViewRowImpl obj) {
        return obj.getEnquiryfaqForEnqViewObj1();
      }

      public void put(InternaluserViewRowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    public abstract Object get(InternaluserViewRowImpl object);

    public abstract void put(InternaluserViewRowImpl object, Object value);

    public int index() {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex() {
      return firstIndex;
    }

    public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues() {
      if (vals == null) {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int ID = AttributesEnum.ID.index();
  public static final int USERID = AttributesEnum.USERID.index();
  public static final int FULLNAME = AttributesEnum.FULLNAME.index();
  public static final int STATUS = AttributesEnum.STATUS.index();
  public static final int PRIMARYROLE = AttributesEnum.PRIMARYROLE.index();
  public static final int EMAIL = AttributesEnum.EMAIL.index();
  public static final int PASSWORD = AttributesEnum.PASSWORD.index();
  public static final int DESIGNATION = AttributesEnum.DESIGNATION.index();
  public static final int DEPTID = AttributesEnum.DEPTID.index();
  public static final int ACCLASTUPDATE = AttributesEnum.ACCLASTUPDATE.index();
  public static final int APPROVERID = AttributesEnum.APPROVERID.index();
  public static final int IDENTITYNO = AttributesEnum.IDENTITYNO.index();
  public static final int PASSPORTNO = AttributesEnum.PASSPORTNO.index();
  public static final int TELEPHONE = AttributesEnum.TELEPHONE.index();
  public static final int MOBILE = AttributesEnum.MOBILE.index();
  public static final int FAX = AttributesEnum.FAX.index();
  public static final int RANK = AttributesEnum.RANK.index();
  public static final int PRIMARYSYSNAME = AttributesEnum.PRIMARYSYSNAME.index();
  public static final int EXTERNALACCESS = AttributesEnum.EXTERNALACCESS.index();
  public static final int PORTALSTATUS = AttributesEnum.PORTALSTATUS.index();
  public static final int LASTLOGINTIME = AttributesEnum.LASTLOGINTIME.index();
  public static final int SYSTEM = AttributesEnum.SYSTEM.index();
  public static final int DEPNAME = AttributesEnum.DepName.index();
  public static final int INTERNALUSERUSERGROUPVIEW = AttributesEnum.InternaluserUsergroupView.index();
  public static final int POLICYBNMUSERSPARTITIONVIEW = AttributesEnum.PolicybnmuserspartitionView.index();
  public static final int REQUESTLISTVIEW = AttributesEnum.RequestlistView.index();
  public static final int DEPARTMENTVIEW = AttributesEnum.DepartmentView.index();
  public static final int ENQUIRYFAQFORENQPENDINGVIEWOBJ = AttributesEnum.EnquiryfaqForEnqPendingViewObj.index();
  public static final int ENQUIRYFAQFORENQVIEWOBJ = AttributesEnum.EnquiryfaqForEnqViewObj.index();
  public static final int ENQUIRYFAQFORENQVIEWOBJ1 = AttributesEnum.EnquiryfaqForEnqViewObj1.index();

  /**
   * This is the default constructor (do not remove).
   */
  public InternaluserViewRowImpl() {
  }

  /**
   * Gets Internaluser entity object.
   * @return the Internaluser
   */
  public EntityImpl getInternaluser() {
    return (EntityImpl)getEntity(0);
  }

  /**
   * Gets the attribute value for ID using the alias name ID.
   * @return the ID
   */
  public String getID() {
    return (String) getAttributeInternal(ID);
  }

  /**
   * Sets <code>value</code> as attribute value for ID using the alias name ID.
   * @param value value to set the ID
   */
  public void setID(String value) {
    setAttributeInternal(ID, value);
  }

  /**
   * Gets the attribute value for USERID using the alias name USERID.
   * @return the USERID
   */
  public String getUSERID() {
    return (String) getAttributeInternal(USERID);
  }

  /**
   * Sets <code>value</code> as attribute value for USERID using the alias name USERID.
   * @param value value to set the USERID
   */
  public void setUSERID(String value) {
    setAttributeInternal(USERID, value);
  }

  /**
   * Gets the attribute value for FULLNAME using the alias name FULLNAME.
   * @return the FULLNAME
   */
  public String getFULLNAME() {
    return (String) getAttributeInternal(FULLNAME);
  }

  /**
   * Sets <code>value</code> as attribute value for FULLNAME using the alias name FULLNAME.
   * @param value value to set the FULLNAME
   */
  public void setFULLNAME(String value) {
    setAttributeInternal(FULLNAME, value);
  }

  /**
   * Gets the attribute value for STATUS using the alias name STATUS.
   * @return the STATUS
   */
  public String getSTATUS() {
    return (String) getAttributeInternal(STATUS);
  }

  /**
   * Sets <code>value</code> as attribute value for STATUS using the alias name STATUS.
   * @param value value to set the STATUS
   */
  public void setSTATUS(String value) {
    setAttributeInternal(STATUS, value);
  }

  /**
   * Gets the attribute value for PRIMARYROLE using the alias name PRIMARYROLE.
   * @return the PRIMARYROLE
   */
  public String getPRIMARYROLE() {
    return (String) getAttributeInternal(PRIMARYROLE);
  }

  /**
   * Sets <code>value</code> as attribute value for PRIMARYROLE using the alias name PRIMARYROLE.
   * @param value value to set the PRIMARYROLE
   */
  public void setPRIMARYROLE(String value) {
    setAttributeInternal(PRIMARYROLE, value);
  }

  /**
   * Gets the attribute value for EMAIL using the alias name EMAIL.
   * @return the EMAIL
   */
  public String getEMAIL() {
    return (String) getAttributeInternal(EMAIL);
  }

  /**
   * Sets <code>value</code> as attribute value for EMAIL using the alias name EMAIL.
   * @param value value to set the EMAIL
   */
  public void setEMAIL(String value) {
    setAttributeInternal(EMAIL, value);
  }

  /**
   * Gets the attribute value for PASSWORD using the alias name PASSWORD.
   * @return the PASSWORD
   */
  public String getPASSWORD() {
    return (String) getAttributeInternal(PASSWORD);
  }

  /**
   * Sets <code>value</code> as attribute value for PASSWORD using the alias name PASSWORD.
   * @param value value to set the PASSWORD
   */
  public void setPASSWORD(String value) {
    setAttributeInternal(PASSWORD, value);
  }

  /**
   * Gets the attribute value for DESIGNATION using the alias name DESIGNATION.
   * @return the DESIGNATION
   */
  public String getDESIGNATION() {
    return (String) getAttributeInternal(DESIGNATION);
  }

  /**
   * Sets <code>value</code> as attribute value for DESIGNATION using the alias name DESIGNATION.
   * @param value value to set the DESIGNATION
   */
  public void setDESIGNATION(String value) {
    setAttributeInternal(DESIGNATION, value);
  }

  /**
   * Gets the attribute value for DEPTID using the alias name DEPTID.
   * @return the DEPTID
   */
  public String getDEPTID() {
    return (String) getAttributeInternal(DEPTID);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPTID using the alias name DEPTID.
   * @param value value to set the DEPTID
   */
  public void setDEPTID(String value) {
    setAttributeInternal(DEPTID, value);
  }

  /**
   * Gets the attribute value for ACCLASTUPDATE using the alias name ACCLASTUPDATE.
   * @return the ACCLASTUPDATE
   */
  public Timestamp getACCLASTUPDATE() {
    return (Timestamp) getAttributeInternal(ACCLASTUPDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for ACCLASTUPDATE using the alias name ACCLASTUPDATE.
   * @param value value to set the ACCLASTUPDATE
   */
  public void setACCLASTUPDATE(Timestamp value) {
    setAttributeInternal(ACCLASTUPDATE, value);
  }

  /**
   * Gets the attribute value for APPROVERID using the alias name APPROVERID.
   * @return the APPROVERID
   */
  public String getAPPROVERID() {
    return (String) getAttributeInternal(APPROVERID);
  }

  /**
   * Sets <code>value</code> as attribute value for APPROVERID using the alias name APPROVERID.
   * @param value value to set the APPROVERID
   */
  public void setAPPROVERID(String value) {
    setAttributeInternal(APPROVERID, value);
  }

  /**
   * Gets the attribute value for IDENTITYNO using the alias name IDENTITYNO.
   * @return the IDENTITYNO
   */
  public String getIDENTITYNO() {
    return (String) getAttributeInternal(IDENTITYNO);
  }

  /**
   * Sets <code>value</code> as attribute value for IDENTITYNO using the alias name IDENTITYNO.
   * @param value value to set the IDENTITYNO
   */
  public void setIDENTITYNO(String value) {
    setAttributeInternal(IDENTITYNO, value);
  }

  /**
   * Gets the attribute value for PASSPORTNO using the alias name PASSPORTNO.
   * @return the PASSPORTNO
   */
  public String getPASSPORTNO() {
    return (String) getAttributeInternal(PASSPORTNO);
  }

  /**
   * Sets <code>value</code> as attribute value for PASSPORTNO using the alias name PASSPORTNO.
   * @param value value to set the PASSPORTNO
   */
  public void setPASSPORTNO(String value) {
    setAttributeInternal(PASSPORTNO, value);
  }

  /**
   * Gets the attribute value for TELEPHONE using the alias name TELEPHONE.
   * @return the TELEPHONE
   */
  public String getTELEPHONE() {
    return (String) getAttributeInternal(TELEPHONE);
  }

  /**
   * Sets <code>value</code> as attribute value for TELEPHONE using the alias name TELEPHONE.
   * @param value value to set the TELEPHONE
   */
  public void setTELEPHONE(String value) {
    setAttributeInternal(TELEPHONE, value);
  }

  /**
   * Gets the attribute value for MOBILE using the alias name MOBILE.
   * @return the MOBILE
   */
  public String getMOBILE() {
    return (String) getAttributeInternal(MOBILE);
  }

  /**
   * Sets <code>value</code> as attribute value for MOBILE using the alias name MOBILE.
   * @param value value to set the MOBILE
   */
  public void setMOBILE(String value) {
    setAttributeInternal(MOBILE, value);
  }

  /**
   * Gets the attribute value for FAX using the alias name FAX.
   * @return the FAX
   */
  public String getFAX() {
    return (String) getAttributeInternal(FAX);
  }

  /**
   * Sets <code>value</code> as attribute value for FAX using the alias name FAX.
   * @param value value to set the FAX
   */
  public void setFAX(String value) {
    setAttributeInternal(FAX, value);
  }

  /**
   * Gets the attribute value for RANK using the alias name RANK.
   * @return the RANK
   */
  public Integer getRANK() {
    return (Integer) getAttributeInternal(RANK);
  }

  /**
   * Sets <code>value</code> as attribute value for RANK using the alias name RANK.
   * @param value value to set the RANK
   */
  public void setRANK(Integer value) {
    setAttributeInternal(RANK, value);
  }

  /**
   * Gets the attribute value for PRIMARYSYSNAME using the alias name PRIMARYSYSNAME.
   * @return the PRIMARYSYSNAME
   */
  public String getPRIMARYSYSNAME() {
    return (String) getAttributeInternal(PRIMARYSYSNAME);
  }

  /**
   * Sets <code>value</code> as attribute value for PRIMARYSYSNAME using the alias name PRIMARYSYSNAME.
   * @param value value to set the PRIMARYSYSNAME
   */
  public void setPRIMARYSYSNAME(String value) {
    setAttributeInternal(PRIMARYSYSNAME, value);
  }

  /**
   * Gets the attribute value for EXTERNALACCESS using the alias name EXTERNALACCESS.
   * @return the EXTERNALACCESS
   */
  public String getEXTERNALACCESS() {
    return (String) getAttributeInternal(EXTERNALACCESS);
  }

  /**
   * Sets <code>value</code> as attribute value for EXTERNALACCESS using the alias name EXTERNALACCESS.
   * @param value value to set the EXTERNALACCESS
   */
  public void setEXTERNALACCESS(String value) {
    setAttributeInternal(EXTERNALACCESS, value);
  }

  /**
   * Gets the attribute value for PORTALSTATUS using the alias name PORTALSTATUS.
   * @return the PORTALSTATUS
   */
  public String getPORTALSTATUS() {
    return (String) getAttributeInternal(PORTALSTATUS);
  }

  /**
   * Sets <code>value</code> as attribute value for PORTALSTATUS using the alias name PORTALSTATUS.
   * @param value value to set the PORTALSTATUS
   */
  public void setPORTALSTATUS(String value) {
    setAttributeInternal(PORTALSTATUS, value);
  }

  /**
   * Gets the attribute value for LASTLOGINTIME using the alias name LASTLOGINTIME.
   * @return the LASTLOGINTIME
   */
  public Timestamp getLASTLOGINTIME() {
    return (Timestamp) getAttributeInternal(LASTLOGINTIME);
  }

  /**
   * Sets <code>value</code> as attribute value for LASTLOGINTIME using the alias name LASTLOGINTIME.
   * @param value value to set the LASTLOGINTIME
   */
  public void setLASTLOGINTIME(Timestamp value) {
    setAttributeInternal(LASTLOGINTIME, value);
  }

  /**
   * Gets the attribute value for SYSTEM using the alias name SYSTEM.
   * @return the SYSTEM
   */
  public String getSYSTEM() {
    return (String) getAttributeInternal(SYSTEM);
  }

  /**
   * Sets <code>value</code> as attribute value for SYSTEM using the alias name SYSTEM.
   * @param value value to set the SYSTEM
   */
  public void setSYSTEM(String value) {
    setAttributeInternal(SYSTEM, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DepName.
   * @return the DepName
   */
  public String getDepName() {
    return (String) getAttributeInternal(DEPNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DepName.
   * @param value value to set the  DepName
   */
  public void setDepName(String value) {
    setAttributeInternal(DEPNAME, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link InternaluserUsergroupView.
   */
  public RowIterator getInternaluserUsergroupView() {
    return (RowIterator)getAttributeInternal(INTERNALUSERUSERGROUPVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link PolicybnmuserspartitionView.
   */
  public RowIterator getPolicybnmuserspartitionView() {
    return (RowIterator)getAttributeInternal(POLICYBNMUSERSPARTITIONVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link RequestlistView.
   */
  public RowIterator getRequestlistView() {
    return (RowIterator)getAttributeInternal(REQUESTLISTVIEW);
  }

  /**
   * Gets the associated <code>Row</code> using master-detail link DepartmentView.
   */
  public Row getDepartmentView() {
    return (Row)getAttributeInternal(DEPARTMENTVIEW);
  }

  /**
   * Sets the master-detail link DepartmentView between this object and <code>value</code>.
   */
  public void setDepartmentView(Row value) {
    setAttributeInternal(DEPARTMENTVIEW, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link EnquiryfaqForEnqPendingViewObj.
   */
  public RowIterator getEnquiryfaqForEnqPendingViewObj() {
    return (RowIterator)getAttributeInternal(ENQUIRYFAQFORENQPENDINGVIEWOBJ);
  }


  /**
   * Gets the associated <code>RowIterator</code> using master-detail link EnquiryfaqForEnqViewObj.
   */
  public RowIterator getEnquiryfaqForEnqViewObj() {
    return (RowIterator)getAttributeInternal(ENQUIRYFAQFORENQVIEWOBJ);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link EnquiryfaqForEnqViewObj1.
   */
  public RowIterator getEnquiryfaqForEnqViewObj1() {
    return (RowIterator)getAttributeInternal(ENQUIRYFAQFORENQVIEWOBJ1);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }
}
