package gov.bnm.rh.views;

import oracle.jbo.Row;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 16 08:29:30 GMT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PolicyinstitutiontypepartitionViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        itemId {
            public Object get(PolicyinstitutiontypepartitionViewRowImpl obj) {
                return obj.getitemId();
            }

            public void put(PolicyinstitutiontypepartitionViewRowImpl obj,
                            Object value) {
                obj.setitemId((String)value);
            }
        },
        id {
            public Object get(PolicyinstitutiontypepartitionViewRowImpl obj) {
                return obj.getid();
            }

            public void put(PolicyinstitutiontypepartitionViewRowImpl obj,
                            Object value) {
                obj.setid((String)value);
            }
        },
        InstitutiontypeName {
            public Object get(PolicyinstitutiontypepartitionViewRowImpl obj) {
                return obj.getInstitutiontypeName();
            }

            public void put(PolicyinstitutiontypepartitionViewRowImpl obj,
                            Object value) {
                obj.setInstitutiontypeName((String)value);
            }
        },
        InstitutiontypeView {
            public Object get(PolicyinstitutiontypepartitionViewRowImpl obj) {
                return obj.getInstitutiontypeView();
            }

            public void put(PolicyinstitutiontypepartitionViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PolicyinstitutiontypepartitionViewRowImpl object);

        public abstract void put(PolicyinstitutiontypepartitionViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ITEMID = AttributesEnum.itemId.index();
    public static final int ID = AttributesEnum.id.index();
    public static final int INSTITUTIONTYPENAME =
        AttributesEnum.InstitutiontypeName.index();
    public static final int INSTITUTIONTYPEVIEW =
        AttributesEnum.InstitutiontypeView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PolicyinstitutiontypepartitionViewRowImpl() {
    }

    /**
     * Gets Policyinstitutiontypepartiti1 entity object.
     * @return the Policyinstitutiontypepartiti1
     */
    public EntityImpl getPolicyinstitutiontypepartiti1() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for itemId using the alias name itemId.
     * @return the itemId
     */
    public String getitemId() {
        return (String)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for itemId using the alias name itemId.
     * @param value value to set the itemId
     */
    public void setitemId(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for id using the alias name id.
     * @return the id
     */
    public String getid() {
        return (String)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for id using the alias name id.
     * @param value value to set the id
     */
    public void setid(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InstitutiontypeName.
     * @return the InstitutiontypeName
     */
    public String getInstitutiontypeName() {
        return (String)getAttributeInternal(INSTITUTIONTYPENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InstitutiontypeName.
     * @param value value to set the  InstitutiontypeName
     */
    public void setInstitutiontypeName(String value) {
        setAttributeInternal(INSTITUTIONTYPENAME, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link InstitutiontypeView.
     */
    public Row getInstitutiontypeView() {
        return (Row)getAttributeInternal(INSTITUTIONTYPEVIEW);
    }

    /**
     * Sets the master-detail link InstitutiontypeView between this object and <code>value</code>.
     */
    public void setInstitutiontypeView(Row value) {
        setAttributeInternal(INSTITUTIONTYPEVIEW, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
