package gov.bnm.rh.views;

import oracle.jbo.Row;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 14 21:19:13 SGT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PolicyRelavantActPartitionViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        itemId {
            public Object get(PolicyRelavantActPartitionViewRowImpl obj) {
                return obj.getitemId();
            }

            public void put(PolicyRelavantActPartitionViewRowImpl obj,
                            Object value) {
                obj.setitemId((String)value);
            }
        }
        ,
        relavantId {
            public Object get(PolicyRelavantActPartitionViewRowImpl obj) {
                return obj.getrelavantId();
            }

            public void put(PolicyRelavantActPartitionViewRowImpl obj,
                            Object value) {
                obj.setrelavantId((String)value);
            }
        }
        ,
        relavantName {
            public Object get(PolicyRelavantActPartitionViewRowImpl obj) {
                return obj.getrelavantName();
            }

            public void put(PolicyRelavantActPartitionViewRowImpl obj,
                            Object value) {
                obj.setrelavantName((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PolicyRelavantActPartitionViewRowImpl object);

        public abstract void put(PolicyRelavantActPartitionViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ITEMID = AttributesEnum.itemId.index();
    public static final int RELAVANTID = AttributesEnum.relavantId.index();
    public static final int RELAVANTNAME = AttributesEnum.relavantName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PolicyRelavantActPartitionViewRowImpl() {
    }

    /**
     * Gets PolicyRelavantActPartition entity object.
     * @return the PolicyRelavantActPartition
     */
    public EntityImpl getPolicyRelavantActPartition() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for itemId using the alias name itemId.
     * @return the itemId
     */
    public String getitemId() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for itemId using the alias name itemId.
     * @param value value to set the itemId
     */
    public void setitemId(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for relavantId using the alias name relavantId.
     * @return the relavantId
     */
    public String getrelavantId() {
        return (String) getAttributeInternal(RELAVANTID);
    }

    /**
     * Sets <code>value</code> as attribute value for relavantId using the alias name relavantId.
     * @param value value to set the relavantId
     */
    public void setrelavantId(String value) {
        setAttributeInternal(RELAVANTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute relavantName.
     * @return the relavantName
     */
    public String getrelavantName() {
        return (String) getAttributeInternal(RELAVANTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute relavantName.
     * @param value value to set the  relavantName
     */
    public void setrelavantName(String value) {
        setAttributeInternal(RELAVANTNAME, value);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
