package gov.bnm.rh.views;

import gov.bnm.rh.entities.PolicyImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 02 06:11:08 GMT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PolicyViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ApplicabilityManualEntry {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getApplicabilityManualEntry();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setApplicabilityManualEntry((String)value);
            }
        }
        ,
        Classification {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getClassification();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setClassification((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setCreatedDate((Timestamp)value);
            }
        }
        ,
        DisplayInWhatsNew {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getDisplayInWhatsNew();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setDisplayInWhatsNew((Boolean)value);
            }
        }
        ,
        DocCategory {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getDocCategory();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setDocCategory((BigDecimal)value);
            }
        }
        ,
        EffectiveDate {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getEffectiveDate();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setEffectiveDate((String)value);
            }
        }
        ,
        NewEffectiveDate {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getNewEffectiveDate();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setNewEffectiveDate((Timestamp)value);
            }
        }
        ,
        ExpiryDate {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getExpiryDate();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setExpiryDate((Timestamp)value);
            }
        }
        ,
        FirstIssuanceDate {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getFirstIssuanceDate();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setFirstIssuanceDate((Timestamp)value);
            }
        }
        ,
        GuidelineTitle {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getGuidelineTitle();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setGuidelineTitle((String)value);
            }
        }
        ,
        Highlights {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getHighlights();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setHighlights((String)value);
            }
        }
        ,
        LastUpdated {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getLastUpdated();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setLastUpdated((Timestamp)value);
            }
        }
        ,
        NewIssuanceDate {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getNewIssuanceDate();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setNewIssuanceDate((Timestamp)value);
            }
        }
        ,
        PolicyURL {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getPolicyURL();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setPolicyURL((String)value);
            }
        }
        ,
        PriorPublishEmailFlag {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getPriorPublishEmailFlag();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setPriorPublishEmailFlag((Boolean)value);
            }
        }
        ,
        PublishToBNM {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getPublishToBNM();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setPublishToBNM((String)value);
            }
        }
        ,
        PublishedEmailFlag {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getPublishedEmailFlag();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setPublishedEmailFlag((Boolean)value);
            }
        }
        ,
        PublishedURL {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getPublishedURL();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setPublishedURL((String)value);
            }
        }
        ,
        ReasonForRejection {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getReasonForRejection();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setReasonForRejection((String)value);
            }
        }
        ,
        RecordStatus {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getRecordStatus();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setRecordStatus((String)value);
            }
        }
        ,
        RefNum {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getRefNum();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setRefNum((String)value);
            }
        }
        ,
        SectionInCharge {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getSectionInCharge();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setSectionInCharge((String)value);
            }
        }
        ,
        SenderEmail {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getSenderEmail();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setSenderEmail((String)value);
            }
        }
        ,
        Summary {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getSummary();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setSummary((String)value);
            }
        }
        ,
        WhatsNewMonths {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getWhatsNewMonths();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setWhatsNewMonths((BigDecimal)value);
            }
        }
        ,
        approverId {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getapproverId();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setapproverId((String)value);
            }
        }
        ,
        createdBy {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getcreatedBy();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setcreatedBy((String)value);
            }
        }
        ,
        isActive {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getisActive();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setisActive((Boolean)value);
            }
        }
        ,
        isAmendmentRecord {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getisAmendmentRecord();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setisAmendmentRecord((Boolean)value);
            }
        }
        ,
        itemId {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getitemId();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setitemId((String)value);
            }
        }
        ,
        keywords {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getkeywords();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setkeywords((String)value);
            }
        }
        ,
        partitionTypeId {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getpartitionTypeId();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setpartitionTypeId((Integer)value);
            }
        }
        ,
        policyId {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getpolicyId();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setpolicyId((String)value);
            }
        }
        ,
        system {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getsystem();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setsystem((String)value);
            }
        }
        ,
        updatedBy {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getupdatedBy();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setupdatedBy((String)value);
            }
        }
        ,
        IssuanceStr {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getIssuanceStr();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setIssuanceStr((String)value);
            }
        }
        ,
        PolicydepartmentpartitionView {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getPolicydepartmentpartitionView();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PolicyinstitutiontypepartitionView {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getPolicyinstitutiontypepartitionView();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PolicysectorcategoryView {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getPolicysectorcategoryView();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AttachedfileView {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getAttachedfileView();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EnquiryfaqForFaqView {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getEnquiryfaqForFaqView();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EnquiryfaqView {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getEnquiryfaqView();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SuperseededpoliciesView {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getSuperseededpoliciesView();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EnquiryfaqForEnqPendingViewObj {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getEnquiryfaqForEnqPendingViewObj();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EnquiryfaqForEnqViewObj {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getEnquiryfaqForEnqViewObj();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PolicyPartitionCompViewObj {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getPolicyPartitionCompViewObj();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RequestlistView {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getRequestlistView();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EnquiryfaqForEnqPolicyViewObj {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getEnquiryfaqForEnqPolicyViewObj();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PolicyRelavantActPartitionView {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getPolicyRelavantActPartitionView();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EnquiryfaqForFaqManView {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getEnquiryfaqForFaqManView();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PolicyIssuringDepartPartitionView {
            public Object get(PolicyViewRowImpl obj) {
                return obj.getPolicyIssuringDepartPartitionView();
            }

            public void put(PolicyViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PolicyViewRowImpl object);

        public abstract void put(PolicyViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int APPLICABILITYMANUALENTRY = AttributesEnum.ApplicabilityManualEntry.index();
    public static final int CLASSIFICATION = AttributesEnum.Classification.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int DISPLAYINWHATSNEW = AttributesEnum.DisplayInWhatsNew.index();
    public static final int DOCCATEGORY = AttributesEnum.DocCategory.index();
    public static final int EFFECTIVEDATE = AttributesEnum.EffectiveDate.index();
    public static final int NEWEFFECTIVEDATE = AttributesEnum.NewEffectiveDate.index();
    public static final int EXPIRYDATE = AttributesEnum.ExpiryDate.index();
    public static final int FIRSTISSUANCEDATE = AttributesEnum.FirstIssuanceDate.index();
    public static final int GUIDELINETITLE = AttributesEnum.GuidelineTitle.index();
    public static final int HIGHLIGHTS = AttributesEnum.Highlights.index();
    public static final int LASTUPDATED = AttributesEnum.LastUpdated.index();
    public static final int NEWISSUANCEDATE = AttributesEnum.NewIssuanceDate.index();
    public static final int POLICYURL = AttributesEnum.PolicyURL.index();
    public static final int PRIORPUBLISHEMAILFLAG = AttributesEnum.PriorPublishEmailFlag.index();
    public static final int PUBLISHTOBNM = AttributesEnum.PublishToBNM.index();
    public static final int PUBLISHEDEMAILFLAG = AttributesEnum.PublishedEmailFlag.index();
    public static final int PUBLISHEDURL = AttributesEnum.PublishedURL.index();
    public static final int REASONFORREJECTION = AttributesEnum.ReasonForRejection.index();
    public static final int RECORDSTATUS = AttributesEnum.RecordStatus.index();
    public static final int REFNUM = AttributesEnum.RefNum.index();
    public static final int SECTIONINCHARGE = AttributesEnum.SectionInCharge.index();
    public static final int SENDEREMAIL = AttributesEnum.SenderEmail.index();
    public static final int SUMMARY = AttributesEnum.Summary.index();
    public static final int WHATSNEWMONTHS = AttributesEnum.WhatsNewMonths.index();
    public static final int APPROVERID = AttributesEnum.approverId.index();
    public static final int CREATEDBY = AttributesEnum.createdBy.index();
    public static final int ISACTIVE = AttributesEnum.isActive.index();
    public static final int ISAMENDMENTRECORD = AttributesEnum.isAmendmentRecord.index();
    public static final int ITEMID = AttributesEnum.itemId.index();
    public static final int KEYWORDS = AttributesEnum.keywords.index();
    public static final int PARTITIONTYPEID = AttributesEnum.partitionTypeId.index();
    public static final int POLICYID = AttributesEnum.policyId.index();
    public static final int SYSTEM = AttributesEnum.system.index();
    public static final int UPDATEDBY = AttributesEnum.updatedBy.index();
    public static final int ISSUANCESTR = AttributesEnum.IssuanceStr.index();
    public static final int POLICYDEPARTMENTPARTITIONVIEW = AttributesEnum.PolicydepartmentpartitionView.index();
    public static final int POLICYINSTITUTIONTYPEPARTITIONVIEW = AttributesEnum.PolicyinstitutiontypepartitionView.index();
    public static final int POLICYSECTORCATEGORYVIEW = AttributesEnum.PolicysectorcategoryView.index();
    public static final int ATTACHEDFILEVIEW = AttributesEnum.AttachedfileView.index();
    public static final int ENQUIRYFAQFORFAQVIEW = AttributesEnum.EnquiryfaqForFaqView.index();
    public static final int ENQUIRYFAQVIEW = AttributesEnum.EnquiryfaqView.index();
    public static final int SUPERSEEDEDPOLICIESVIEW = AttributesEnum.SuperseededpoliciesView.index();
    public static final int ENQUIRYFAQFORENQPENDINGVIEWOBJ = AttributesEnum.EnquiryfaqForEnqPendingViewObj.index();
    public static final int ENQUIRYFAQFORENQVIEWOBJ = AttributesEnum.EnquiryfaqForEnqViewObj.index();
    public static final int POLICYPARTITIONCOMPVIEWOBJ = AttributesEnum.PolicyPartitionCompViewObj.index();
    public static final int REQUESTLISTVIEW = AttributesEnum.RequestlistView.index();
    public static final int ENQUIRYFAQFORENQPOLICYVIEWOBJ = AttributesEnum.EnquiryfaqForEnqPolicyViewObj.index();
    public static final int POLICYRELAVANTACTPARTITIONVIEW = AttributesEnum.PolicyRelavantActPartitionView.index();
    public static final int ENQUIRYFAQFORFAQMANVIEW = AttributesEnum.EnquiryfaqForFaqManView.index();
    public static final int POLICYISSURINGDEPARTPARTITIONVIEW = AttributesEnum.PolicyIssuringDepartPartitionView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PolicyViewRowImpl() {
    }

    /**
   * Gets Policy entity object.
   * @return the Policy
   */
  public PolicyImpl getPolicy() {
    return (PolicyImpl)getEntity(0);
  }

  /**
   * Gets the attribute value for the calculated attribute itemId.
   * @return the itemId
   */
  public String getitemId() {
    return (String) getAttributeInternal(ITEMID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute itemId.
   * @param value value to set the  itemId
   */
  public void setitemId(String value) {
    setAttributeInternal(ITEMID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute policyId.
   * @return the policyId
   */
  public String getpolicyId() {
    return (String) getAttributeInternal(POLICYID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute policyId.
   * @param value value to set the  policyId
   */
  public void setpolicyId(String value) {
    setAttributeInternal(POLICYID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute GuidelineTitle.
   * @return the GuidelineTitle
   */
  public String getGuidelineTitle() {
    return (String) getAttributeInternal(GUIDELINETITLE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute GuidelineTitle.
   * @param value value to set the  GuidelineTitle
   */
  public void setGuidelineTitle(String value) {
    setAttributeInternal(GUIDELINETITLE, value);
  }


  /**
   * Gets the attribute value for the calculated attribute Summary.
   * @return the Summary
   */
  public String getSummary() {
    return (String) getAttributeInternal(SUMMARY);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute Summary.
   * @param value value to set the  Summary
   */
  public void setSummary(String value) {
    setAttributeInternal(SUMMARY, value);
  }

  /**
   * Gets the attribute value for approverId using the alias name approverId.
   * @return the approverId
   */
  public String getapproverId() {
    return (String) getAttributeInternal(APPROVERID);
  }

  /**
   * Sets <code>value</code> as attribute value for approverId using the alias name approverId.
   * @param value value to set the approverId
   */
  public void setapproverId(String value) {
    setAttributeInternal(APPROVERID, value);
  }

  /**
   * Gets the attribute value for createdBy using the alias name createdBy.
   * @return the createdBy
   */
  public String getcreatedBy() {
    return (String) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for createdBy using the alias name createdBy.
   * @param value value to set the createdBy
   */
  public void setcreatedBy(String value) {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for the calculated attribute Classification.
   * @return the Classification
   */
  public String getClassification() {
    return (String) getAttributeInternal(CLASSIFICATION);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute Classification.
   * @param value value to set the  Classification
   */
  public void setClassification(String value) {
    setAttributeInternal(CLASSIFICATION, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ApplicabilityManualEntry.
   * @return the ApplicabilityManualEntry
   */
  public String getApplicabilityManualEntry() {
    return (String) getAttributeInternal(APPLICABILITYMANUALENTRY);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute ApplicabilityManualEntry.
   * @param value value to set the  ApplicabilityManualEntry
   */
  public void setApplicabilityManualEntry(String value) {
    setAttributeInternal(APPLICABILITYMANUALENTRY, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayInWhatsNew.
   * @return the DisplayInWhatsNew
   */
  public Boolean getDisplayInWhatsNew() {
    return (Boolean) getAttributeInternal(DISPLAYINWHATSNEW);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayInWhatsNew.
   * @param value value to set the  DisplayInWhatsNew
   */
  public void setDisplayInWhatsNew(Boolean value) {
    setAttributeInternal(DISPLAYINWHATSNEW, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ExpiryDate.
   * @return the ExpiryDate
   */
  public Timestamp getExpiryDate() {
    return (Timestamp) getAttributeInternal(EXPIRYDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute ExpiryDate.
   * @param value value to set the  ExpiryDate
   */
  public void setExpiryDate(Timestamp value) {
    setAttributeInternal(EXPIRYDATE, value);
  }

  /**
   * Gets the attribute value for the calculated attribute CreatedDate.
   * @return the CreatedDate
   */
  public Timestamp getCreatedDate() {
    return (Timestamp) getAttributeInternal(CREATEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute CreatedDate.
   * @param value value to set the  CreatedDate
   */
  public void setCreatedDate(Timestamp value) {
    setAttributeInternal(CREATEDDATE, value);
  }

  /**
   * Gets the attribute value for the calculated attribute LastUpdated.
   * @return the LastUpdated
   */
  public Timestamp getLastUpdated() {
    return (Timestamp) getAttributeInternal(LASTUPDATED);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdated.
   * @param value value to set the  LastUpdated
   */
  public void setLastUpdated(Timestamp value) {
    setAttributeInternal(LASTUPDATED, value);
  }


  /**
   * Gets the attribute value for the calculated attribute SenderEmail.
   * @return the SenderEmail
   */
  public String getSenderEmail() {
    return (String) getAttributeInternal(SENDEREMAIL);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute SenderEmail.
   * @param value value to set the  SenderEmail
   */
  public void setSenderEmail(String value) {
    setAttributeInternal(SENDEREMAIL, value);
  }


  /**
   * Gets the attribute value for the calculated attribute NewIssuanceDate.
   * @return the NewIssuanceDate
   */
  public Timestamp getNewIssuanceDate() {
    return (Timestamp) getAttributeInternal(NEWISSUANCEDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute NewIssuanceDate.
   * @param value value to set the  NewIssuanceDate
   */
  public void setNewIssuanceDate(Timestamp value) {
    setAttributeInternal(NEWISSUANCEDATE, value);
  }


  /**
   * Gets the attribute value for the calculated attribute RecordStatus.
   * @return the RecordStatus
   */
  public String getRecordStatus() {
    return (String) getAttributeInternal(RECORDSTATUS);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute RecordStatus.
   * @param value value to set the  RecordStatus
   */
  public void setRecordStatus(String value) {
    setAttributeInternal(RECORDSTATUS, value);
  }

  /**
   * Gets the attribute value for the calculated attribute FirstIssuanceDate.
   * @return the FirstIssuanceDate
   */
  public Timestamp getFirstIssuanceDate() {
    return (Timestamp) getAttributeInternal(FIRSTISSUANCEDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute FirstIssuanceDate.
   * @param value value to set the  FirstIssuanceDate
   */
  public void setFirstIssuanceDate(Timestamp value) {
    setAttributeInternal(FIRSTISSUANCEDATE, value);
  }

  /**
   * Gets the attribute value for the calculated attribute PublishToBNM.
   * @return the PublishToBNM
   */
  public String getPublishToBNM() {
    return (String) getAttributeInternal(PUBLISHTOBNM);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute PublishToBNM.
   * @param value value to set the  PublishToBNM
   */
  public void setPublishToBNM(String value) {
    setAttributeInternal(PUBLISHTOBNM, value);
  }

  /**
   * Gets the attribute value for the calculated attribute Highlights.
   * @return the Highlights
   */
  public String getHighlights() {
    return (String) getAttributeInternal(HIGHLIGHTS);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute Highlights.
   * @param value value to set the  Highlights
   */
  public void setHighlights(String value) {
    setAttributeInternal(HIGHLIGHTS, value);
  }

  /**
   * Gets the attribute value for the calculated attribute PriorPublishEmailFlag.
   * @return the PriorPublishEmailFlag
   */
  public Boolean getPriorPublishEmailFlag() {
    return (Boolean) getAttributeInternal(PRIORPUBLISHEMAILFLAG);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute PriorPublishEmailFlag.
   * @param value value to set the  PriorPublishEmailFlag
   */
  public void setPriorPublishEmailFlag(Boolean value) {
    setAttributeInternal(PRIORPUBLISHEMAILFLAG, value);
  }

  /**
   * Gets the attribute value for the calculated attribute PublishedEmailFlag.
   * @return the PublishedEmailFlag
   */
  public Boolean getPublishedEmailFlag() {
    return (Boolean) getAttributeInternal(PUBLISHEDEMAILFLAG);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute PublishedEmailFlag.
   * @param value value to set the  PublishedEmailFlag
   */
  public void setPublishedEmailFlag(Boolean value) {
    setAttributeInternal(PUBLISHEDEMAILFLAG, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ReasonForRejection.
   * @return the ReasonForRejection
   */
  public String getReasonForRejection() {
    return (String) getAttributeInternal(REASONFORREJECTION);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute ReasonForRejection.
   * @param value value to set the  ReasonForRejection
   */
  public void setReasonForRejection(String value) {
    setAttributeInternal(REASONFORREJECTION, value);
  }

  /**
   * Gets the attribute value for the calculated attribute isAmendmentRecord.
   * @return the isAmendmentRecord
   */
  public Boolean getisAmendmentRecord() {
    return (Boolean) getAttributeInternal(ISAMENDMENTRECORD);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute isAmendmentRecord.
   * @param value value to set the  isAmendmentRecord
   */
  public void setisAmendmentRecord(Boolean value) {
    setAttributeInternal(ISAMENDMENTRECORD, value);
  }


  /**
   * Gets the attribute value for EffectiveDate using the alias name EffectiveDate.
   * @return the EffectiveDate
   */
    public String getEffectiveDate() {
        return (String)getAttributeInternal(EFFECTIVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EffectiveDate using the alias name EffectiveDate.
     * @param value value to set the EffectiveDate
     */
    public void setEffectiveDate(String value) {
        setAttributeInternal(EFFECTIVEDATE, value);
    }


  /**
   * Gets the attribute value for the calculated attribute PolicyURL.
   * @return the PolicyURL
   */
  public String getPolicyURL() {
    return (String) getAttributeInternal(POLICYURL);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute PolicyURL.
   * @param value value to set the  PolicyURL
   */
  public void setPolicyURL(String value) {
    setAttributeInternal(POLICYURL, value);
  }


  /**
   * Gets the attribute value for the calculated attribute PublishedURL.
   * @return the PublishedURL
   */
  public String getPublishedURL() {
    return (String) getAttributeInternal(PUBLISHEDURL);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute PublishedURL.
   * @param value value to set the  PublishedURL
   */
  public void setPublishedURL(String value) {
    setAttributeInternal(PUBLISHEDURL, value);
  }

  /**
   * Gets the attribute value for the calculated attribute isActive.
   * @return the isActive
   */
  public Boolean getisActive() {
    return (Boolean) getAttributeInternal(ISACTIVE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute isActive.
   * @param value value to set the  isActive
   */
  public void setisActive(Boolean value) {
    setAttributeInternal(ISACTIVE, value);
  }

  /**
   * Gets the attribute value for the calculated attribute RefNum.
   * @return the RefNum
   */
  public String getRefNum() {
    return (String) getAttributeInternal(REFNUM);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute RefNum.
   * @param value value to set the  RefNum
   */
  public void setRefNum(String value) {
    setAttributeInternal(REFNUM, value);
  }


  /**
   * Gets the attribute value for SectionInCharge using the alias name SectionInCharge.
   * @return the SectionInCharge
   */
  public String getSectionInCharge() {
    return (String) getAttributeInternal(SECTIONINCHARGE);
  }

  /**
   * Sets <code>value</code> as attribute value for SectionInCharge using the alias name SectionInCharge.
   * @param value value to set the SectionInCharge
   */
  public void setSectionInCharge(String value) {
    setAttributeInternal(SECTIONINCHARGE, value);
  }

  /**
   * Gets the attribute value for the calculated attribute keywords.
   * @return the keywords
   */
  public String getkeywords() {
    return (String) getAttributeInternal(KEYWORDS);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute keywords.
   * @param value value to set the  keywords
   */
  public void setkeywords(String value) {
    setAttributeInternal(KEYWORDS, value);
  }

  /**
   * Gets the attribute value for the calculated attribute partitionTypeId.
   * @return the partitionTypeId
   */
  public Integer getpartitionTypeId() {
    return (Integer) getAttributeInternal(PARTITIONTYPEID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute partitionTypeId.
   * @param value value to set the  partitionTypeId
   */
  public void setpartitionTypeId(Integer value) {
    setAttributeInternal(PARTITIONTYPEID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute system.
   * @return the system
   */
  public String getsystem() {
    return (String) getAttributeInternal(SYSTEM);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute system.
   * @param value value to set the  system
   */
  public void setsystem(String value) {
    setAttributeInternal(SYSTEM, value);
  }

  /**
   * Gets the attribute value for updatedBy using the alias name updatedBy.
   * @return the updatedBy
   */
  public String getupdatedBy() {
    return (String) getAttributeInternal(UPDATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for updatedBy using the alias name updatedBy.
   * @param value value to set the updatedBy
   */
  public void setupdatedBy(String value) {
    setAttributeInternal(UPDATEDBY, value);
  }

  /**
   * Gets the attribute value for the calculated attribute IssuanceStr.
   * @return the IssuanceStr
   */
  public String getIssuanceStr() {
    return (String) getAttributeInternal(ISSUANCESTR);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute IssuanceStr.
   * @param value value to set the  IssuanceStr
   */
  public void setIssuanceStr(String value) {
    setAttributeInternal(ISSUANCESTR, value);
  }

    /**
     * Gets the attribute value for NewEffectiveDate using the alias name NewEffectiveDate.
     * @return the NewEffectiveDate
     */
    public Timestamp getNewEffectiveDate() {
        return (Timestamp) getAttributeInternal(NEWEFFECTIVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for NewEffectiveDate using the alias name NewEffectiveDate.
     * @param value value to set the NewEffectiveDate
     */
    public void setNewEffectiveDate(Timestamp value) {
        setAttributeInternal(NEWEFFECTIVEDATE, value);
    }

    /**
     * Gets the attribute value for WhatsNewMonths using the alias name WhatsNewMonths.
     * @return the WhatsNewMonths
     */
  public BigDecimal getWhatsNewMonths() {
    return (BigDecimal) getAttributeInternal(WHATSNEWMONTHS);
  }

  /**
   * Sets <code>value</code> as attribute value for WhatsNewMonths using the alias name WhatsNewMonths.
   * @param value value to set the WhatsNewMonths
   */
  public void setWhatsNewMonths(BigDecimal value) {
    setAttributeInternal(WHATSNEWMONTHS, value);
  }

  /**
   * Gets the attribute value for DocCategory using the alias name DocCategory.
   * @return the DocCategory
   */
  public BigDecimal getDocCategory() {
    return (BigDecimal) getAttributeInternal(DOCCATEGORY);
  }

  /**
   * Sets <code>value</code> as attribute value for DocCategory using the alias name DocCategory.
   * @param value value to set the DocCategory
   */
  public void setDocCategory(BigDecimal value) {
    setAttributeInternal(DOCCATEGORY, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link PolicydepartmentpartitionView.
   */
    public RowIterator getPolicydepartmentpartitionView() {
        return (RowIterator)getAttributeInternal(POLICYDEPARTMENTPARTITIONVIEW);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link PolicyinstitutiontypepartitionView.
     */
    public Row getPolicyinstitutiontypepartitionView() {
        return (Row)getAttributeInternal(POLICYINSTITUTIONTYPEPARTITIONVIEW);
    }

    /**
     * Sets the master-detail link PolicyinstitutiontypepartitionView between this object and <code>value</code>.
     */
    public void setPolicyinstitutiontypepartitionView(Row value) {
        setAttributeInternal(POLICYINSTITUTIONTYPEPARTITIONVIEW, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PolicysectorcategoryView.
     */
    public RowIterator getPolicysectorcategoryView() {
        return (RowIterator)getAttributeInternal(POLICYSECTORCATEGORYVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AttachedfileView.
     */
    public RowIterator getAttachedfileView() {
        return (RowIterator)getAttributeInternal(ATTACHEDFILEVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EnquiryfaqForFaqView.
     */
    public RowIterator getEnquiryfaqForFaqView() {
        return (RowIterator)getAttributeInternal(ENQUIRYFAQFORFAQVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EnquiryfaqView.
     */
    public RowIterator getEnquiryfaqView() {
        return (RowIterator)getAttributeInternal(ENQUIRYFAQVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EnquiryfaqForFaqManView.
     */
    public RowIterator getEnquiryfaqForFaqManView() {
        return (RowIterator)getAttributeInternal(ENQUIRYFAQFORFAQMANVIEW);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PolicyIssuringDepartPartitionView.
     */
    public RowIterator getPolicyIssuringDepartPartitionView() {
        return (RowIterator)getAttributeInternal(POLICYISSURINGDEPARTPARTITIONVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PolicyRelavantActPartitionView.
     */
    public RowIterator getPolicyRelavantActPartitionView() {
        return (RowIterator)getAttributeInternal(POLICYRELAVANTACTPARTITIONVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EnquiryfaqForEnqPolicyViewObj.
     */
  public RowIterator getEnquiryfaqForEnqPolicyViewObj() {
    return (RowIterator)getAttributeInternal(ENQUIRYFAQFORENQPOLICYVIEWOBJ);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link RequestlistView.
   */
    public RowIterator getRequestlistView() {
        return (RowIterator)getAttributeInternal(REQUESTLISTVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PolicyPartitionCompViewObj.
     */
    public RowIterator getPolicyPartitionCompViewObj() {
        return (RowIterator)getAttributeInternal(POLICYPARTITIONCOMPVIEWOBJ);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EnquiryfaqForEnqPendingViewObj.
     */
    public RowIterator getEnquiryfaqForEnqPendingViewObj() {
        return (RowIterator)getAttributeInternal(ENQUIRYFAQFORENQPENDINGVIEWOBJ);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EnquiryfaqForEnqViewObj.
     */
    public RowIterator getEnquiryfaqForEnqViewObj() {
        return (RowIterator)getAttributeInternal(ENQUIRYFAQFORENQVIEWOBJ);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SuperseededpoliciesView.
     */
    public RowIterator getSuperseededpoliciesView() {
        return (RowIterator)getAttributeInternal(SUPERSEEDEDPOLICIESVIEW);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
