package gov.bnm.rh.views;

import oracle.jbo.Row;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 13 07:07:53 GMT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PolicydepartmentpartitionViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        departmentId {
            public Object get(PolicydepartmentpartitionViewRowImpl obj) {
                return obj.getdepartmentId();
            }

            public void put(PolicydepartmentpartitionViewRowImpl obj,
                            Object value) {
                obj.setdepartmentId((String)value);
            }
        },
        itemId {
            public Object get(PolicydepartmentpartitionViewRowImpl obj) {
                return obj.getitemId();
            }

            public void put(PolicydepartmentpartitionViewRowImpl obj,
                            Object value) {
                obj.setitemId((String)value);
            }
        },
        DepartmentName {
            public Object get(PolicydepartmentpartitionViewRowImpl obj) {
                return obj.getDepartmentName();
            }

            public void put(PolicydepartmentpartitionViewRowImpl obj,
                            Object value) {
                obj.setDepartmentName((String)value);
            }
        },
        DepartmentView {
            public Object get(PolicydepartmentpartitionViewRowImpl obj) {
                return obj.getDepartmentView();
            }

            public void put(PolicydepartmentpartitionViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PolicydepartmentpartitionViewRowImpl object);

        public abstract void put(PolicydepartmentpartitionViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DEPARTMENTID = AttributesEnum.departmentId.index();
    public static final int ITEMID = AttributesEnum.itemId.index();
    public static final int DEPARTMENTNAME =
        AttributesEnum.DepartmentName.index();
    public static final int DEPARTMENTVIEW =
        AttributesEnum.DepartmentView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PolicydepartmentpartitionViewRowImpl() {
    }

    /**
     * Gets Policydepartmentpartition entity object.
     * @return the Policydepartmentpartition
     */
    public EntityImpl getPolicydepartmentpartition() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for departmentId using the alias name departmentId.
     * @return the departmentId
     */
    public String getdepartmentId() {
        return (String)getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for departmentId using the alias name departmentId.
     * @param value value to set the departmentId
     */
    public void setdepartmentId(String value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for itemId using the alias name itemId.
     * @return the itemId
     */
    public String getitemId() {
        return (String)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for itemId using the alias name itemId.
     * @param value value to set the itemId
     */
    public void setitemId(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DepartmentName.
     * @return the DepartmentName
     */
    public String getDepartmentName() {
        return (String)getAttributeInternal(DEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DepartmentName.
     * @param value value to set the  DepartmentName
     */
    public void setDepartmentName(String value) {
        setAttributeInternal(DEPARTMENTNAME, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link DepartmentView.
     */
    public Row getDepartmentView() {
        return (Row)getAttributeInternal(DEPARTMENTVIEW);
    }

    /**
     * Sets the master-detail link DepartmentView between this object and <code>value</code>.
     */
    public void setDepartmentView(Row value) {
        setAttributeInternal(DEPARTMENTVIEW, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
