package RHmodel;

import RHmodel.common.view.ItemlistViewRowImpl;

import RHmodel.common.view.PolicyViewRowImpl;


import java.util.Date;

import java.sql.Timestamp;

import oracle.jbo.TooManyObjectsException;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 11 04:24:49 GMT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RhAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RhAppModuleImpl() {
    }

    /**
     * Container's getter for AttachedfileView1.
     * @return AttachedfileView1
     */
    public ViewObjectImpl getAttachedfileView1() {
        return (ViewObjectImpl)findViewObject("AttachedfileView1");
    }

    /**
     * Container's getter for BnmuserUsergroupView1.
     * @return BnmuserUsergroupView1
     */
    public ViewObjectImpl getBnmuserUsergroupView1() {
        return (ViewObjectImpl)findViewObject("BnmuserUsergroupView1");
    }

    /**
     * Container's getter for BnmuserView1.
     * @return BnmuserView1
     */
    public ViewObjectImpl getBnmuserView1() {
        return (ViewObjectImpl)findViewObject("BnmuserView1");
    }

    /**
     * Container's getter for CategoriesView1.
     * @return CategoriesView1
     */
    public ViewObjectImpl getCategoriesView1() {
        return (ViewObjectImpl)findViewObject("CategoriesView1");
    }

    /**
     * Container's getter for DepartmentView1.
     * @return DepartmentView1
     */
    public ViewObjectImpl getDepartmentView1() {
        return (ViewObjectImpl)findViewObject("DepartmentView1");
    }

    /**
     * Container's getter for EnquiriesView1.
     * @return EnquiriesView1
     */
    public ViewObjectImpl getEnquiriesView1() {
        return (ViewObjectImpl)findViewObject("EnquiriesView1");
    }

    /**
     * Container's getter for EnquiryfaqView1.
     * @return EnquiryfaqView1
     */
    public ViewObjectImpl getEnquiryfaqView1() {
        return (ViewObjectImpl)findViewObject("EnquiryfaqView1");
    }

    /**
     * Container's getter for ExternaluserView1.
     * @return ExternaluserView1
     */
    public ViewObjectImpl getExternaluserView1() {
        return (ViewObjectImpl)findViewObject("ExternaluserView1");
    }

    /**
     * Container's getter for Function1View1.
     * @return Function1View1
     */
    public ViewObjectImpl getFunction1View1() {
        return (ViewObjectImpl)findViewObject("Function1View1");
    }

    /**
     * Container's getter for FunctionUsergroupView1.
     * @return FunctionUsergroupView1
     */
    public ViewObjectImpl getFunctionUsergroupView1() {
        return (ViewObjectImpl)findViewObject("FunctionUsergroupView1");
    }

    /**
     * Container's getter for InstitutiontypeView1.
     * @return InstitutiontypeView1
     */
    public ViewObjectImpl getInstitutiontypeView1() {
        return (ViewObjectImpl)findViewObject("InstitutiontypeView1");
    }

    /**
     * Container's getter for ItemlistView1.
     * @return ItemlistView1
     */
    public ViewObjectImpl getItemlistView1() {
        return (ViewObjectImpl)findViewObject("ItemlistView1");
    }

    /**
     * Container's getter for ItemtypelistView1.
     * @return ItemtypelistView1
     */
    public ViewObjectImpl getItemtypelistView1() {
        return (ViewObjectImpl)findViewObject("ItemtypelistView1");
    }

    /**
     * Container's getter for L1browserView1.
     * @return L1browserView1
     */
    public ViewObjectImpl getL1browserView1() {
        return (ViewObjectImpl)findViewObject("L1browserView1");
    }

    /**
     * Container's getter for L2browserView1.
     * @return L2browserView1
     */
    public ViewObjectImpl getL2browserView1() {
        return (ViewObjectImpl)findViewObject("L2browserView1");
    }

    /**
     * Container's getter for L3browserView1.
     * @return L3browserView1
     */
    public ViewObjectImpl getL3browserView1() {
        return (ViewObjectImpl)findViewObject("L3browserView1");
    }

    /**
     * Container's getter for L4browserView1.
     * @return L4browserView1
     */
    public ViewObjectImpl getL4browserView1() {
        return (ViewObjectImpl)findViewObject("L4browserView1");
    }

    /**
     * Container's getter for LookuppropertiesView1.
     * @return LookuppropertiesView1
     */
    public ViewObjectImpl getLookuppropertiesView1() {
        return (ViewObjectImpl)findViewObject("LookuppropertiesView1");
    }

    /**
     * Container's getter for OrganizationView1.
     * @return OrganizationView1
     */
    public ViewObjectImpl getOrganizationView1() {
        return (ViewObjectImpl)findViewObject("OrganizationView1");
    }

    /**
     * Container's getter for PartitiontypelistView1.
     * @return PartitiontypelistView1
     */
    public ViewObjectImpl getPartitiontypelistView1() {
        return (ViewObjectImpl)findViewObject("PartitiontypelistView1");
    }

    /**
     * Container's getter for PcollControlView1.
     * @return PcollControlView1
     */
    public ViewObjectImpl getPcollControlView1() {
        return (ViewObjectImpl)findViewObject("PcollControlView1");
    }

    /**
     * Container's getter for PolicyView1.
     * @return PolicyView1
     */
    public ViewObjectImpl getPolicyView1() {
        return (ViewObjectImpl)findViewObject("PolicyView1");
    }

    /**
     * Container's getter for PolicyamendmentsView1.
     * @return PolicyamendmentsView1
     */
    public ViewObjectImpl getPolicyamendmentsView1() {
        return (ViewObjectImpl)findViewObject("PolicyamendmentsView1");
    }

    /**
     * Container's getter for PolicydepartmentpartitionView1.
     * @return PolicydepartmentpartitionView1
     */
    public ViewObjectImpl getPolicydepartmentpartitionView1() {
        return (ViewObjectImpl)findViewObject("PolicydepartmentpartitionView1");
    }

    /**
     * Container's getter for PolicyinstitutiontypepartitionView1.
     * @return PolicyinstitutiontypepartitionView1
     */
    public ViewObjectImpl getPolicyinstitutiontypepartitionView1() {
        return (ViewObjectImpl)findViewObject("PolicyinstitutiontypepartitionView1");
    }

    /**
     * Container's getter for PsTxnView1.
     * @return PsTxnView1
     */
    public ViewObjectImpl getPsTxnView1() {
        return (ViewObjectImpl)findViewObject("PsTxnView1");
    }

    /**
     * Container's getter for SectorcategorysmeView1.
     * @return SectorcategorysmeView1
     */
    public ViewObjectImpl getSectorcategorysmeView1() {
        return (ViewObjectImpl)findViewObject("SectorcategorysmeView1");
    }

    /**
     * Container's getter for SectorsView1.
     * @return SectorsView1
     */
    public ViewObjectImpl getSectorsView1() {
        return (ViewObjectImpl)findViewObject("SectorsView1");
    }

    /**
     * Container's getter for TbladftokenView1.
     * @return TbladftokenView1
     */
    public ViewObjectImpl getTbladftokenView1() {
        return (ViewObjectImpl)findViewObject("TbladftokenView1");
    }

    /**
     * Container's getter for UserUsergroupView1.
     * @return UserUsergroupView1
     */
    public ViewObjectImpl getUserUsergroupView1() {
        return (ViewObjectImpl)findViewObject("UserUsergroupView1");
    }

    /**
     * Container's getter for UsergroupView1.
     * @return UsergroupView1
     */
    public ViewObjectImpl getUsergroupView1() {
        return (ViewObjectImpl)findViewObject("UsergroupView1");
    }

    /**
     * Container's getter for BnmuserUsergroupView2.
     * @return BnmuserUsergroupView2
     */
    public ViewObjectImpl getBnmuserUsergroupView2() {
        return (ViewObjectImpl)findViewObject("BnmuserUsergroupView2");
    }

    /**
     * Container's getter for BnmuserView2.
     * @return BnmuserView2
     */
    public ViewObjectImpl getBnmuserView2() {
        return (ViewObjectImpl)findViewObject("BnmuserView2");
    }

    /**
     * Container's getter for EnquiriesView2.
     * @return EnquiriesView2
     */
    public ViewObjectImpl getEnquiriesView2() {
        return (ViewObjectImpl)findViewObject("EnquiriesView2");
    }

    /**
     * Container's getter for FunctionUsergroupView2.
     * @return FunctionUsergroupView2
     */
    public ViewObjectImpl getFunctionUsergroupView2() {
        return (ViewObjectImpl)findViewObject("FunctionUsergroupView2");
    }

    /**
     * Container's getter for L2browserView2.
     * @return L2browserView2
     */
    public ViewObjectImpl getL2browserView2() {
        return (ViewObjectImpl)findViewObject("L2browserView2");
    }

    /**
     * Container's getter for L3browserView2.
     * @return L3browserView2
     */
    public ViewObjectImpl getL3browserView2() {
        return (ViewObjectImpl)findViewObject("L3browserView2");
    }

    /**
     * Container's getter for L4browserView2.
     * @return L4browserView2
     */
    public ViewObjectImpl getL4browserView2() {
        return (ViewObjectImpl)findViewObject("L4browserView2");
    }

    /**
     * Container's getter for ExternaluserView2.
     * @return ExternaluserView2
     */
    public ViewObjectImpl getExternaluserView2() {
        return (ViewObjectImpl)findViewObject("ExternaluserView2");
    }

    /**
     * Container's getter for EnquiryfaqView2.
     * @return EnquiryfaqView2
     */
    public ViewObjectImpl getEnquiryfaqView2() {
        return (ViewObjectImpl)findViewObject("EnquiryfaqView2");
    }

    /**
     * Container's getter for PolicyView2.
     * @return PolicyView2
     */
    public ViewObjectImpl getPolicyView2() {
        return (ViewObjectImpl)findViewObject("PolicyView2");
    }

    /**
     * Container's getter for EnquiryfaqView3.
     * @return EnquiryfaqView3
     */
    public ViewObjectImpl getEnquiryfaqView3() {
        return (ViewObjectImpl)findViewObject("EnquiryfaqView3");
    }

    /**
     * Container's getter for PolicydepartmentpartitionView2.
     * @return PolicydepartmentpartitionView2
     */
    public ViewObjectImpl getPolicydepartmentpartitionView2() {
        return (ViewObjectImpl)findViewObject("PolicydepartmentpartitionView2");
    }

    /**
     * Container's getter for PolicydepartmentpartitionView3.
     * @return PolicydepartmentpartitionView3
     */
    public ViewObjectImpl getPolicydepartmentpartitionView3() {
        return (ViewObjectImpl)findViewObject("PolicydepartmentpartitionView3");
    }

    /**
     * Container's getter for PolicyinstitutiontypepartitionView2.
     * @return PolicyinstitutiontypepartitionView2
     */
    public ViewObjectImpl getPolicyinstitutiontypepartitionView2() {
        return (ViewObjectImpl)findViewObject("PolicyinstitutiontypepartitionView2");
    }

    /**
     * Container's getter for EnquiriesView3.
     * @return EnquiriesView3
     */
    public ViewObjectImpl getEnquiriesView3() {
        return (ViewObjectImpl)findViewObject("EnquiriesView3");
    }

    /**
     * Container's getter for SectorcategorysmeView2.
     * @return SectorcategorysmeView2
     */
    public ViewObjectImpl getSectorcategorysmeView2() {
        return (ViewObjectImpl)findViewObject("SectorcategorysmeView2");
    }

    /**
     * Container's getter for EnquiriesView4.
     * @return EnquiriesView4
     */
    public ViewObjectImpl getEnquiriesView4() {
        return (ViewObjectImpl)findViewObject("EnquiriesView4");
    }

    /**
     * Container's getter for OrganizationView2.
     * @return OrganizationView2
     */
    public ViewObjectImpl getOrganizationView2() {
        return (ViewObjectImpl)findViewObject("OrganizationView2");
    }

    /**
     * Container's getter for SectorcategorysmeView3.
     * @return SectorcategorysmeView3
     */
    public ViewObjectImpl getSectorcategorysmeView3() {
        return (ViewObjectImpl)findViewObject("SectorcategorysmeView3");
    }

    /**
     * Container's getter for ExternaluserView3.
     * @return ExternaluserView3
     */
    public ViewObjectImpl getExternaluserView3() {
        return (ViewObjectImpl)findViewObject("ExternaluserView3");
    }

    /**
     * Container's getter for FunctionUsergroupView3.
     * @return FunctionUsergroupView3
     */
    public ViewObjectImpl getFunctionUsergroupView3() {
        return (ViewObjectImpl)findViewObject("FunctionUsergroupView3");
    }

    /**
     * Container's getter for BnmuserUsergroupView3.
     * @return BnmuserUsergroupView3
     */
    public ViewObjectImpl getBnmuserUsergroupView3() {
        return (ViewObjectImpl)findViewObject("BnmuserUsergroupView3");
    }

    /**
     * Container's getter for UserUsergroupView2.
     * @return UserUsergroupView2
     */
    public ViewObjectImpl getUserUsergroupView2() {
        return (ViewObjectImpl)findViewObject("UserUsergroupView2");
    }

    /**
     * Container's getter for UserUsergroupView3.
     * @return UserUsergroupView3
     */
    public ViewObjectImpl getUserUsergroupView3() {
        return (ViewObjectImpl)findViewObject("UserUsergroupView3");
    }

    /**
     * Container's getter for AttachedfileView2.
     * @return AttachedfileView2
     */
    public ViewObjectImpl getAttachedfileView2() {
        return (ViewObjectImpl)findViewObject("AttachedfileView2");
    }

    /**
     * Container's getter for AttachedfileView3.
     * @return AttachedfileView3
     */
    public ViewObjectImpl getAttachedfileView3() {
        return (ViewObjectImpl)findViewObject("AttachedfileView3");
    }

    /**
     * Container's getter for OrganizationView3.
     * @return OrganizationView3
     */
    public ViewObjectImpl getOrganizationView3() {
        return (ViewObjectImpl)findViewObject("OrganizationView3");
    }

    /**
     * Container's getter for PolicyinstitutiontypepartitionView3.
     * @return PolicyinstitutiontypepartitionView3
     */
    public ViewObjectImpl getPolicyinstitutiontypepartitionView3() {
        return (ViewObjectImpl)findViewObject("PolicyinstitutiontypepartitionView3");
    }

    /**
     * Container's getter for L2browserView3.
     * @return L2browserView3
     */
    public ViewObjectImpl getL2browserView3() {
        return (ViewObjectImpl)findViewObject("L2browserView3");
    }

    /**
     * Container's getter for PolicyView3.
     * @return PolicyView3
     */
    public ViewObjectImpl getPolicyView3() {
        return (ViewObjectImpl)findViewObject("PolicyView3");
    }

    /**
     * Container's getter for L4browserView3.
     * @return L4browserView3
     */
    public ViewObjectImpl getL4browserView3() {
        return (ViewObjectImpl)findViewObject("L4browserView3");
    }

    /**
     * Container's getter for L3browserView3.
     * @return L3browserView3
     */
    public ViewObjectImpl getL3browserView3() {
        return (ViewObjectImpl)findViewObject("L3browserView3");
    }

    /**
     * Container's getter for L1browserView2.
     * @return L1browserView2
     */
    public ViewObjectImpl getL1browserView2() {
        return (ViewObjectImpl)findViewObject("L1browserView2");
    }

    /**
     * Container's getter for ItemtypelistView2.
     * @return ItemtypelistView2
     */
    public ViewObjectImpl getItemtypelistView2() {
        return (ViewObjectImpl)findViewObject("ItemtypelistView2");
    }

    /**
     * Container's getter for BNMUSERUSERGROUPBNMUSERFK1Link1.
     * @return BNMUSERUSERGROUPBNMUSERFK1Link1
     */
    public ViewLinkImpl getBNMUSERUSERGROUPBNMUSERFK1Link1() {
        return (ViewLinkImpl)findViewLink("BNMUSERUSERGROUPBNMUSERFK1Link1");
    }

    /**
     * Container's getter for BNMUSERDEPARTMENTFK1Link1.
     * @return BNMUSERDEPARTMENTFK1Link1
     */
    public ViewLinkImpl getBNMUSERDEPARTMENTFK1Link1() {
        return (ViewLinkImpl)findViewLink("BNMUSERDEPARTMENTFK1Link1");
    }

    /**
     * Container's getter for FKEnquiriesCategoriesLink1.
     * @return FKEnquiriesCategoriesLink1
     */
    public ViewLinkImpl getFKEnquiriesCategoriesLink1() {
        return (ViewLinkImpl)findViewLink("FKEnquiriesCategoriesLink1");
    }

    /**
     * Container's getter for FUNCTIONUSERGROUPFUNCTIONFK1Link1.
     * @return FUNCTIONUSERGROUPFUNCTIONFK1Link1
     */
    public ViewLinkImpl getFUNCTIONUSERGROUPFUNCTIONFK1Link1() {
        return (ViewLinkImpl)findViewLink("FUNCTIONUSERGROUPFUNCTIONFK1Link1");
    }

    /**
     * Container's getter for L2BrowserL1BrowserFKLink1.
     * @return L2BrowserL1BrowserFKLink1
     */
    public ViewLinkImpl getL2BrowserL1BrowserFKLink1() {
        return (ViewLinkImpl)findViewLink("L2BrowserL1BrowserFKLink1");
    }

    /**
     * Container's getter for L3BrowserL2BrowserFKLink1.
     * @return L3BrowserL2BrowserFKLink1
     */
    public ViewLinkImpl getL3BrowserL2BrowserFKLink1() {
        return (ViewLinkImpl)findViewLink("L3BrowserL2BrowserFKLink1");
    }

    /**
     * Container's getter for L4BrowserL3BrowserFKLink1.
     * @return L4BrowserL3BrowserFKLink1
     */
    public ViewLinkImpl getL4BrowserL3BrowserFKLink1() {
        return (ViewLinkImpl)findViewLink("L4BrowserL3BrowserFKLink1");
    }

    /**
     * Container's getter for EXTERNALUSEROrganizationFK1Link1.
     * @return EXTERNALUSEROrganizationFK1Link1
     */
    public ViewLinkImpl getEXTERNALUSEROrganizationFK1Link1() {
        return (ViewLinkImpl)findViewLink("EXTERNALUSEROrganizationFK1Link1");
    }

    /**
     * Container's getter for EnquiryFaqPolicyFKLink1.
     * @return EnquiryFaqPolicyFKLink1
     */
    public ViewLinkImpl getEnquiryFaqPolicyFKLink1() {
        return (ViewLinkImpl)findViewLink("EnquiryFaqPolicyFKLink1");
    }

    /**
     * Container's getter for PolicyPartitionTypeListFKLink1.
     * @return PolicyPartitionTypeListFKLink1
     */
    public ViewLinkImpl getPolicyPartitionTypeListFKLink1() {
        return (ViewLinkImpl)findViewLink("PolicyPartitionTypeListFKLink1");
    }

    /**
     * Container's getter for EnquiryFaqPolicyAmendmentsFKLink1.
     * @return EnquiryFaqPolicyAmendmentsFKLink1
     */
    public ViewLinkImpl getEnquiryFaqPolicyAmendmentsFKLink1() {
        return (ViewLinkImpl)findViewLink("EnquiryFaqPolicyAmendmentsFKLink1");
    }

    /**
     * Container's getter for PolicyDepartmentPartitionDEPARTMENTFK1Link1.
     * @return PolicyDepartmentPartitionDEPARTMENTFK1Link1
     */
    public ViewLinkImpl getPolicyDepartmentPartitionDEPARTMENTFK1Link1() {
        return (ViewLinkImpl)findViewLink("PolicyDepartmentPartitionDEPARTMENTFK1Link1");
    }

    /**
     * Container's getter for PolicyDepartmentPartitionFKLink1.
     * @return PolicyDepartmentPartitionFKLink1
     */
    public ViewLinkImpl getPolicyDepartmentPartitionFKLink1() {
        return (ViewLinkImpl)findViewLink("PolicyDepartmentPartitionFKLink1");
    }

    /**
     * Container's getter for PolicyInstitutionTypePartiFK1Link1.
     * @return PolicyInstitutionTypePartiFK1Link1
     */
    public ViewLinkImpl getPolicyInstitutionTypePartiFK1Link1() {
        return (ViewLinkImpl)findViewLink("PolicyInstitutionTypePartiFK1Link1");
    }

    /**
     * Container's getter for FKEnquiriesSectorCategorySMELink1.
     * @return FKEnquiriesSectorCategorySMELink1
     */
    public ViewLinkImpl getFKEnquiriesSectorCategorySMELink1() {
        return (ViewLinkImpl)findViewLink("FKEnquiriesSectorCategorySMELink1");
    }

    /**
     * Container's getter for FKSectorCategorySMECategoriesLink1.
     * @return FKSectorCategorySMECategoriesLink1
     */
    public ViewLinkImpl getFKSectorCategorySMECategoriesLink1() {
        return (ViewLinkImpl)findViewLink("FKSectorCategorySMECategoriesLink1");
    }

    /**
     * Container's getter for FKEnquiriesSectorsLink1.
     * @return FKEnquiriesSectorsLink1
     */
    public ViewLinkImpl getFKEnquiriesSectorsLink1() {
        return (ViewLinkImpl)findViewLink("FKEnquiriesSectorsLink1");
    }

    /**
     * Container's getter for OrganizationSectorsFK1Link1.
     * @return OrganizationSectorsFK1Link1
     */
    public ViewLinkImpl getOrganizationSectorsFK1Link1() {
        return (ViewLinkImpl)findViewLink("OrganizationSectorsFK1Link1");
    }

    /**
     * Container's getter for FKSectorCategorySMESectorsLink1.
     * @return FKSectorCategorySMESectorsLink1
     */
    public ViewLinkImpl getFKSectorCategorySMESectorsLink1() {
        return (ViewLinkImpl)findViewLink("FKSectorCategorySMESectorsLink1");
    }

    /**
     * Container's getter for EXTERNALUSERSectorsFK1Link1.
     * @return EXTERNALUSERSectorsFK1Link1
     */
    public ViewLinkImpl getEXTERNALUSERSectorsFK1Link1() {
        return (ViewLinkImpl)findViewLink("EXTERNALUSERSectorsFK1Link1");
    }

    /**
     * Container's getter for FUNCTIONUSERGROUPUSERGROUPFK1Link1.
     * @return FUNCTIONUSERGROUPUSERGROUPFK1Link1
     */
    public ViewLinkImpl getFUNCTIONUSERGROUPUSERGROUPFK1Link1() {
        return (ViewLinkImpl)findViewLink("FUNCTIONUSERGROUPUSERGROUPFK1Link1");
    }

    /**
     * Container's getter for BNMUSERUSERGROUPUSERGROUPFK1Link1.
     * @return BNMUSERUSERGROUPUSERGROUPFK1Link1
     */
    public ViewLinkImpl getBNMUSERUSERGROUPUSERGROUPFK1Link1() {
        return (ViewLinkImpl)findViewLink("BNMUSERUSERGROUPUSERGROUPFK1Link1");
    }

    /**
     * Container's getter for USERUSERGROUPEXTERNALUSERFK1Link1.
     * @return USERUSERGROUPEXTERNALUSERFK1Link1
     */
    public ViewLinkImpl getUSERUSERGROUPEXTERNALUSERFK1Link1() {
        return (ViewLinkImpl)findViewLink("USERUSERGROUPEXTERNALUSERFK1Link1");
    }

    /**
     * Container's getter for USERUSERGROUPUSERGROUPFK1Link1.
     * @return USERUSERGROUPUSERGROUPFK1Link1
     */
    public ViewLinkImpl getUSERUSERGROUPUSERGROUPFK1Link1() {
        return (ViewLinkImpl)findViewLink("USERUSERGROUPUSERGROUPFK1Link1");
    }

    /**
     * Container's getter for attachedFilePolicyFKLink1.
     * @return attachedFilePolicyFKLink1
     */
    public ViewLinkImpl getattachedFilePolicyFKLink1() {
        return (ViewLinkImpl)findViewLink("attachedFilePolicyFKLink1");
    }

    /**
     * Container's getter for attachedFileFKLink1.
     * @return attachedFileFKLink1
     */
    public ViewLinkImpl getattachedFileFKLink1() {
        return (ViewLinkImpl)findViewLink("attachedFileFKLink1");
    }

    /**
     * Container's getter for OrganizationinstitutionTypeFK1Link1.
     * @return OrganizationinstitutionTypeFK1Link1
     */
    public ViewLinkImpl getOrganizationinstitutionTypeFK1Link1() {
        return (ViewLinkImpl)findViewLink("OrganizationinstitutionTypeFK1Link1");
    }

    /**
     * Container's getter for PolicyInstitutionTypePartitFKLink1.
     * @return PolicyInstitutionTypePartitFKLink1
     */
    public ViewLinkImpl getPolicyInstitutionTypePartitFKLink1() {
        return (ViewLinkImpl)findViewLink("PolicyInstitutionTypePartitFKLink1");
    }

    /**
     * Container's getter for L2BrowseritemListFKLink1.
     * @return L2BrowseritemListFKLink1
     */
    public ViewLinkImpl getL2BrowseritemListFKLink1() {
        return (ViewLinkImpl)findViewLink("L2BrowseritemListFKLink1");
    }

    /**
     * Container's getter for PolicyitemListFKLink1.
     * @return PolicyitemListFKLink1
     */
    public ViewLinkImpl getPolicyitemListFKLink1() {
        return (ViewLinkImpl)findViewLink("PolicyitemListFKLink1");
    }

    /**
     * Container's getter for L4BrowseritemListFKLink1.
     * @return L4BrowseritemListFKLink1
     */
    public ViewLinkImpl getL4BrowseritemListFKLink1() {
        return (ViewLinkImpl)findViewLink("L4BrowseritemListFKLink1");
    }

    /**
     * Container's getter for L3BrowseritemListFKLink1.
     * @return L3BrowseritemListFKLink1
     */
    public ViewLinkImpl getL3BrowseritemListFKLink1() {
        return (ViewLinkImpl)findViewLink("L3BrowseritemListFKLink1");
    }

    /**
     * Container's getter for L1BrowseritemListFKLink1.
     * @return L1BrowseritemListFKLink1
     */
    public ViewLinkImpl getL1BrowseritemListFKLink1() {
        return (ViewLinkImpl)findViewLink("L1BrowseritemListFKLink1");
    }

    /**
     * Container's getter for itemTypeListitemListFKLink1.
     * @return itemTypeListitemListFKLink1
     */
    public ViewLinkImpl getitemTypeListitemListFKLink1() {
        return (ViewLinkImpl)findViewLink("itemTypeListitemListFKLink1");
    }

    public void createNewPolicy(String policy) {

        try {
            System.out.println("policy::" + policy);
            ViewObjectImpl itemlistVO = this.getItemlistView1();
            ItemlistViewRowImpl itemlistRow =
                (ItemlistViewRowImpl)itemlistVO.createRow();
            itemlistRow.setitemid(policy);
            itemlistRow.setcreateDate(new Timestamp(new Date().getTime()));
            ViewObjectImpl policyVO = this.getPolicyView3();
            PolicyViewRowImpl policyRow =
                (PolicyViewRowImpl)policyVO.createRow();
            policyRow.setitemId(policy);
            policyRow.setpolicyId(policy);
        } catch (TooManyObjectsException ex) {
            System.out.println("TooManyObjectsException::" + ex.getMessage());
        }
        return;
    }
}
