package gov.bnm.rh.entities;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 16 14:53:53 SGT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PolicyImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        itemId,
        policyId,
        GuidelineTitle,
        EffectiveDate,
        PolicyURL,
        Summary,
        Classification,
        ApplicabilityManualEntry,
        DisplayInWhatsNew,
        ExpiryDate,
        CreatedDate,
        LastUpdated,
        keywords,
        partitionTypeId,
        system,
        PublishedURL,
        isActive,
        RefNum,
        SenderEmail,
        NewIssuanceDate,
        RecordStatus,
        FirstIssuanceDate,
        PublishToBNM,
        Highlights,
        PriorPublishEmailFlag,
        PublishedEmailFlag,
        ReasonForRejection,
        isAmendmentRecord,
        createdBy,
        updatedBy,
        approverId,
        WhatsNewMonths,
        DocCategory,
        SectionInCharge,
        NewEffectiveDate,
        Partitiontypelist,
        Policydepartmentpartition,
        Policyinstitutiontypepartition,
        Policysectorcategory,
        Attachedfile,
        Itemlist,
        Policybusinesssectorpartition1,
        Policyorganizationpartition,
        Enquiryfaq,
        EnquiryfaqForFaq,
        Policybnmuserspartition,
        PolicyRelavantActPartition,
        PolicyIssuringDepartPartition;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ITEMID = AttributesEnum.itemId.index();
    public static final int POLICYID = AttributesEnum.policyId.index();
    public static final int GUIDELINETITLE = AttributesEnum.GuidelineTitle.index();
    public static final int EFFECTIVEDATE = AttributesEnum.EffectiveDate.index();
    public static final int POLICYURL = AttributesEnum.PolicyURL.index();
    public static final int SUMMARY = AttributesEnum.Summary.index();
    public static final int CLASSIFICATION = AttributesEnum.Classification.index();
    public static final int APPLICABILITYMANUALENTRY = AttributesEnum.ApplicabilityManualEntry.index();
    public static final int DISPLAYINWHATSNEW = AttributesEnum.DisplayInWhatsNew.index();
    public static final int EXPIRYDATE = AttributesEnum.ExpiryDate.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATED = AttributesEnum.LastUpdated.index();
    public static final int KEYWORDS = AttributesEnum.keywords.index();
    public static final int PARTITIONTYPEID = AttributesEnum.partitionTypeId.index();
    public static final int SYSTEM = AttributesEnum.system.index();
    public static final int PUBLISHEDURL = AttributesEnum.PublishedURL.index();
    public static final int ISACTIVE = AttributesEnum.isActive.index();
    public static final int REFNUM = AttributesEnum.RefNum.index();
    public static final int SENDEREMAIL = AttributesEnum.SenderEmail.index();
    public static final int NEWISSUANCEDATE = AttributesEnum.NewIssuanceDate.index();
    public static final int RECORDSTATUS = AttributesEnum.RecordStatus.index();
    public static final int FIRSTISSUANCEDATE = AttributesEnum.FirstIssuanceDate.index();
    public static final int PUBLISHTOBNM = AttributesEnum.PublishToBNM.index();
    public static final int HIGHLIGHTS = AttributesEnum.Highlights.index();
    public static final int PRIORPUBLISHEMAILFLAG = AttributesEnum.PriorPublishEmailFlag.index();
    public static final int PUBLISHEDEMAILFLAG = AttributesEnum.PublishedEmailFlag.index();
    public static final int REASONFORREJECTION = AttributesEnum.ReasonForRejection.index();
    public static final int ISAMENDMENTRECORD = AttributesEnum.isAmendmentRecord.index();
    public static final int CREATEDBY = AttributesEnum.createdBy.index();
    public static final int UPDATEDBY = AttributesEnum.updatedBy.index();
    public static final int APPROVERID = AttributesEnum.approverId.index();
    public static final int WHATSNEWMONTHS = AttributesEnum.WhatsNewMonths.index();
    public static final int DOCCATEGORY = AttributesEnum.DocCategory.index();
    public static final int SECTIONINCHARGE = AttributesEnum.SectionInCharge.index();
    public static final int NEWEFFECTIVEDATE = AttributesEnum.NewEffectiveDate.index();
    public static final int PARTITIONTYPELIST = AttributesEnum.Partitiontypelist.index();
    public static final int POLICYDEPARTMENTPARTITION = AttributesEnum.Policydepartmentpartition.index();
    public static final int POLICYINSTITUTIONTYPEPARTITION = AttributesEnum.Policyinstitutiontypepartition.index();
    public static final int POLICYSECTORCATEGORY = AttributesEnum.Policysectorcategory.index();
    public static final int ATTACHEDFILE = AttributesEnum.Attachedfile.index();
    public static final int ITEMLIST = AttributesEnum.Itemlist.index();
    public static final int POLICYBUSINESSSECTORPARTITION1 = AttributesEnum.Policybusinesssectorpartition1.index();
    public static final int POLICYORGANIZATIONPARTITION = AttributesEnum.Policyorganizationpartition.index();
    public static final int ENQUIRYFAQ = AttributesEnum.Enquiryfaq.index();
    public static final int ENQUIRYFAQFORFAQ = AttributesEnum.EnquiryfaqForFaq.index();
    public static final int POLICYBNMUSERSPARTITION = AttributesEnum.Policybnmuserspartition.index();
    public static final int POLICYRELAVANTACTPARTITION = AttributesEnum.PolicyRelavantActPartition.index();
    public static final int POLICYISSURINGDEPARTPARTITION = AttributesEnum.PolicyIssuringDepartPartition.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PolicyImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("gov.bnm.rh.entities.Policy");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for itemId, using the alias name itemId.
     * @return the itemId
     */
    public String getitemId() {
        return (String)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for itemId.
     * @param value value to set the itemId
     */
    public void setitemId(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for policyId, using the alias name policyId.
     * @return the policyId
     */
    public String getpolicyId() {
        return (String)getAttributeInternal(POLICYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for policyId.
     * @param value value to set the policyId
     */
    public void setpolicyId(String value) {
        setAttributeInternal(POLICYID, value);
    }

    /**
     * Gets the attribute value for GuidelineTitle, using the alias name GuidelineTitle.
     * @return the GuidelineTitle
     */
    public String getGuidelineTitle() {
        return (String)getAttributeInternal(GUIDELINETITLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GuidelineTitle.
     * @param value value to set the GuidelineTitle
     */
    public void setGuidelineTitle(String value) {
        setAttributeInternal(GUIDELINETITLE, value);
    }

    /**
     * Gets the attribute value for EffectiveDate, using the alias name EffectiveDate.
     * @return the EffectiveDate
     */
    public String getEffectiveDate() {
        return (String)getAttributeInternal(EFFECTIVEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveDate.
     * @param value value to set the EffectiveDate
     */
    public void setEffectiveDate(String value) {
        setAttributeInternal(EFFECTIVEDATE, value);
    }

    /**
     * Gets the attribute value for PolicyURL, using the alias name PolicyURL.
     * @return the PolicyURL
     */
    public String getPolicyURL() {
        return (String)getAttributeInternal(POLICYURL);
    }

    /**
     * Sets <code>value</code> as the attribute value for PolicyURL.
     * @param value value to set the PolicyURL
     */
    public void setPolicyURL(String value) {
        setAttributeInternal(POLICYURL, value);
    }

    /**
     * Gets the attribute value for Summary, using the alias name Summary.
     * @return the Summary
     */
    public String getSummary() {
        return (String)getAttributeInternal(SUMMARY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Summary.
     * @param value value to set the Summary
     */
    public void setSummary(String value) {
        setAttributeInternal(SUMMARY, value);
    }

    /**
     * Gets the attribute value for Classification, using the alias name Classification.
     * @return the Classification
     */
    public String getClassification() {
        return (String)getAttributeInternal(CLASSIFICATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Classification.
     * @param value value to set the Classification
     */
    public void setClassification(String value) {
        setAttributeInternal(CLASSIFICATION, value);
    }

    /**
     * Gets the attribute value for ApplicabilityManualEntry, using the alias name ApplicabilityManualEntry.
     * @return the ApplicabilityManualEntry
     */
    public String getApplicabilityManualEntry() {
        return (String)getAttributeInternal(APPLICABILITYMANUALENTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApplicabilityManualEntry.
     * @param value value to set the ApplicabilityManualEntry
     */
    public void setApplicabilityManualEntry(String value) {
        setAttributeInternal(APPLICABILITYMANUALENTRY, value);
    }

    /**
     * Gets the attribute value for DisplayInWhatsNew, using the alias name DisplayInWhatsNew.
     * @return the DisplayInWhatsNew
     */
    public Boolean getDisplayInWhatsNew() {
        return (Boolean)getAttributeInternal(DISPLAYINWHATSNEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for DisplayInWhatsNew.
     * @param value value to set the DisplayInWhatsNew
     */
    public void setDisplayInWhatsNew(Boolean value) {
        setAttributeInternal(DISPLAYINWHATSNEW, value);
    }

    /**
     * Gets the attribute value for ExpiryDate, using the alias name ExpiryDate.
     * @return the ExpiryDate
     */
    public Timestamp getExpiryDate() {
        return (Timestamp)getAttributeInternal(EXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpiryDate.
     * @param value value to set the ExpiryDate
     */
    public void setExpiryDate(Timestamp value) {
        setAttributeInternal(EXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdated, using the alias name LastUpdated.
     * @return the LastUpdated
     */
    public Timestamp getLastUpdated() {
        return (Timestamp)getAttributeInternal(LASTUPDATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdated.
     * @param value value to set the LastUpdated
     */
    public void setLastUpdated(Timestamp value) {
        setAttributeInternal(LASTUPDATED, value);
    }

    /**
     * Gets the attribute value for keywords, using the alias name keywords.
     * @return the keywords
     */
    public String getkeywords() {
        return (String)getAttributeInternal(KEYWORDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for keywords.
     * @param value value to set the keywords
     */
    public void setkeywords(String value) {
        setAttributeInternal(KEYWORDS, value);
    }

    /**
     * Gets the attribute value for partitionTypeId, using the alias name partitionTypeId.
     * @return the partitionTypeId
     */
    public Integer getpartitionTypeId() {
        return (Integer)getAttributeInternal(PARTITIONTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for partitionTypeId.
     * @param value value to set the partitionTypeId
     */
    public void setpartitionTypeId(Integer value) {
        setAttributeInternal(PARTITIONTYPEID, value);
    }

    /**
     * Gets the attribute value for system, using the alias name system.
     * @return the system
     */
    public String getsystem() {
        return (String)getAttributeInternal(SYSTEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for system.
     * @param value value to set the system
     */
    public void setsystem(String value) {
        setAttributeInternal(SYSTEM, value);
    }

    /**
     * Gets the attribute value for PublishedURL, using the alias name PublishedURL.
     * @return the PublishedURL
     */
    public String getPublishedURL() {
        return (String)getAttributeInternal(PUBLISHEDURL);
    }

    /**
     * Sets <code>value</code> as the attribute value for PublishedURL.
     * @param value value to set the PublishedURL
     */
    public void setPublishedURL(String value) {
        setAttributeInternal(PUBLISHEDURL, value);
    }

    /**
     * Gets the attribute value for isActive, using the alias name isActive.
     * @return the isActive
     */
    public Boolean getisActive() {
        return (Boolean)getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for isActive.
     * @param value value to set the isActive
     */
    public void setisActive(Boolean value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for RefNum, using the alias name RefNum.
     * @return the RefNum
     */
    public String getRefNum() {
        return (String)getAttributeInternal(REFNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefNum.
     * @param value value to set the RefNum
     */
    public void setRefNum(String value) {
        setAttributeInternal(REFNUM, value);
    }

    /**
     * Gets the attribute value for SenderEmail, using the alias name SenderEmail.
     * @return the SenderEmail
     */
    public String getSenderEmail() {
        return (String)getAttributeInternal(SENDEREMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for SenderEmail.
     * @param value value to set the SenderEmail
     */
    public void setSenderEmail(String value) {
        setAttributeInternal(SENDEREMAIL, value);
    }

    /**
     * Gets the attribute value for NewIssuanceDate, using the alias name NewIssuanceDate.
     * @return the NewIssuanceDate
     */
    public Timestamp getNewIssuanceDate() {
        return (Timestamp)getAttributeInternal(NEWISSUANCEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NewIssuanceDate.
     * @param value value to set the NewIssuanceDate
     */
    public void setNewIssuanceDate(Timestamp value) {
        setAttributeInternal(NEWISSUANCEDATE, value);
    }

    /**
     * Gets the attribute value for RecordStatus, using the alias name RecordStatus.
     * @return the RecordStatus
     */
    public String getRecordStatus() {
        return (String)getAttributeInternal(RECORDSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for RecordStatus.
     * @param value value to set the RecordStatus
     */
    public void setRecordStatus(String value) {
        setAttributeInternal(RECORDSTATUS, value);
    }

    /**
     * Gets the attribute value for FirstIssuanceDate, using the alias name FirstIssuanceDate.
     * @return the FirstIssuanceDate
     */
    public Timestamp getFirstIssuanceDate() {
        return (Timestamp)getAttributeInternal(FIRSTISSUANCEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FirstIssuanceDate.
     * @param value value to set the FirstIssuanceDate
     */
    public void setFirstIssuanceDate(Timestamp value) {
        setAttributeInternal(FIRSTISSUANCEDATE, value);
    }

    /**
     * Gets the attribute value for PublishToBNM, using the alias name PublishToBNM.
     * @return the PublishToBNM
     */
    public String getPublishToBNM() {
        return (String)getAttributeInternal(PUBLISHTOBNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for PublishToBNM.
     * @param value value to set the PublishToBNM
     */
    public void setPublishToBNM(String value) {
        setAttributeInternal(PUBLISHTOBNM, value);
    }

    /**
     * Gets the attribute value for Highlights, using the alias name Highlights.
     * @return the Highlights
     */
    public String getHighlights() {
        return (String)getAttributeInternal(HIGHLIGHTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Highlights.
     * @param value value to set the Highlights
     */
    public void setHighlights(String value) {
        setAttributeInternal(HIGHLIGHTS, value);
    }

    /**
     * Gets the attribute value for PriorPublishEmailFlag, using the alias name PriorPublishEmailFlag.
     * @return the PriorPublishEmailFlag
     */
    public Boolean getPriorPublishEmailFlag() {
        return (Boolean)getAttributeInternal(PRIORPUBLISHEMAILFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for PriorPublishEmailFlag.
     * @param value value to set the PriorPublishEmailFlag
     */
    public void setPriorPublishEmailFlag(Boolean value) {
        setAttributeInternal(PRIORPUBLISHEMAILFLAG, value);
    }

    /**
     * Gets the attribute value for PublishedEmailFlag, using the alias name PublishedEmailFlag.
     * @return the PublishedEmailFlag
     */
    public Boolean getPublishedEmailFlag() {
        return (Boolean)getAttributeInternal(PUBLISHEDEMAILFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for PublishedEmailFlag.
     * @param value value to set the PublishedEmailFlag
     */
    public void setPublishedEmailFlag(Boolean value) {
        setAttributeInternal(PUBLISHEDEMAILFLAG, value);
    }

    /**
     * Gets the attribute value for ReasonForRejection, using the alias name ReasonForRejection.
     * @return the ReasonForRejection
     */
    public String getReasonForRejection() {
        return (String)getAttributeInternal(REASONFORREJECTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReasonForRejection.
     * @param value value to set the ReasonForRejection
     */
    public void setReasonForRejection(String value) {
        setAttributeInternal(REASONFORREJECTION, value);
    }

    /**
     * Gets the attribute value for isAmendmentRecord, using the alias name isAmendmentRecord.
     * @return the isAmendmentRecord
     */
    public Boolean getisAmendmentRecord() {
        return (Boolean)getAttributeInternal(ISAMENDMENTRECORD);
    }

    /**
     * Sets <code>value</code> as the attribute value for isAmendmentRecord.
     * @param value value to set the isAmendmentRecord
     */
    public void setisAmendmentRecord(Boolean value) {
        setAttributeInternal(ISAMENDMENTRECORD, value);
    }

    /**
     * Gets the attribute value for createdBy, using the alias name createdBy.
     * @return the createdBy
     */
    public String getcreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for createdBy.
     * @param value value to set the createdBy
     */
    public void setcreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for updatedBy, using the alias name updatedBy.
     * @return the updatedBy
     */
    public String getupdatedBy() {
        return (String)getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for updatedBy.
     * @param value value to set the updatedBy
     */
    public void setupdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for approverId, using the alias name approverId.
     * @return the approverId
     */
    public String getapproverId() {
        return (String)getAttributeInternal(APPROVERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for approverId.
     * @param value value to set the approverId
     */
    public void setapproverId(String value) {
        setAttributeInternal(APPROVERID, value);
    }

    /**
     * Gets the attribute value for WhatsNewMonths, using the alias name WhatsNewMonths.
     * @return the WhatsNewMonths
     */
    public BigDecimal getWhatsNewMonths() {
        return (BigDecimal)getAttributeInternal(WHATSNEWMONTHS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WhatsNewMonths.
     * @param value value to set the WhatsNewMonths
     */
    public void setWhatsNewMonths(BigDecimal value) {
        setAttributeInternal(WHATSNEWMONTHS, value);
    }

    /**
     * Gets the attribute value for DocCategory, using the alias name DocCategory.
     * @return the DocCategory
     */
    public BigDecimal getDocCategory() {
        return (BigDecimal)getAttributeInternal(DOCCATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocCategory.
     * @param value value to set the DocCategory
     */
    public void setDocCategory(BigDecimal value) {
        setAttributeInternal(DOCCATEGORY, value);
    }

    /**
     * Gets the attribute value for SectionInCharge, using the alias name SectionInCharge.
     * @return the SectionInCharge
     */
    public String getSectionInCharge() {
        return (String)getAttributeInternal(SECTIONINCHARGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SectionInCharge.
     * @param value value to set the SectionInCharge
     */
    public void setSectionInCharge(String value) {
        setAttributeInternal(SECTIONINCHARGE, value);
    }

    /**
     * Gets the attribute value for NewEffectiveDate, using the alias name NewEffectiveDate.
     * @return the NewEffectiveDate
     */
    public Timestamp getNewEffectiveDate() {
        return (Timestamp)getAttributeInternal(NEWEFFECTIVEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NewEffectiveDate.
     * @param value value to set the NewEffectiveDate
     */
    public void setNewEffectiveDate(Timestamp value) {
        setAttributeInternal(NEWEFFECTIVEDATE, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getPartitiontypelist() {
        return (EntityImpl)getAttributeInternal(PARTITIONTYPELIST);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setPartitiontypelist(EntityImpl value) {
        setAttributeInternal(PARTITIONTYPELIST, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPolicydepartmentpartition() {
        return (RowIterator)getAttributeInternal(POLICYDEPARTMENTPARTITION);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getPolicyinstitutiontypepartition() {
        return (EntityImpl)getAttributeInternal(POLICYINSTITUTIONTYPEPARTITION);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setPolicyinstitutiontypepartition(EntityImpl value) {
        setAttributeInternal(POLICYINSTITUTIONTYPEPARTITION, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPolicysectorcategory() {
        return (RowIterator)getAttributeInternal(POLICYSECTORCATEGORY);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getAttachedfile() {
        return (RowIterator)getAttributeInternal(ATTACHEDFILE);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getItemlist() {
        return (EntityImpl)getAttributeInternal(ITEMLIST);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setItemlist(EntityImpl value) {
        setAttributeInternal(ITEMLIST, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPolicybusinesssectorpartition1() {
        return (RowIterator)getAttributeInternal(POLICYBUSINESSSECTORPARTITION1);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPolicyorganizationpartition() {
        return (RowIterator)getAttributeInternal(POLICYORGANIZATIONPARTITION);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getEnquiryfaq() {
        return (RowIterator)getAttributeInternal(ENQUIRYFAQ);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getEnquiryfaqForFaq() {
        return (RowIterator)getAttributeInternal(ENQUIRYFAQFORFAQ);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPolicybnmuserspartition() {
        return (RowIterator)getAttributeInternal(POLICYBNMUSERSPARTITION);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPolicyRelavantActPartition() {
        return (RowIterator)getAttributeInternal(POLICYRELAVANTACTPARTITION);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPolicyIssuringDepartPartition() {
        return (RowIterator)getAttributeInternal(POLICYISSURINGDEPARTPARTITION);
    }

    /**
     * @param itemId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String itemId) {
        return new Key(new Object[]{itemId});
    }


}
