package gov.bnm.rh.client;

import gov.bnm.rh.common.RegBookAppModule;

import java.util.List;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 29 08:11:11 GMT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegBookAppModuleClient extends ApplicationModuleImpl implements RegBookAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public RegBookAppModuleClient() {
    }


    //    public void filterByPolicyIdOnlyPolicyTable(String itemid) {
    //    Object _ret =
    //      this.riInvokeExportedMethod(this,"filterByPolicyIdOnlyPolicyTable",new String [] {"java.lang.String"},new Object[] {itemid});
    //    return;
    //  }


    public void getAgingResponseManagementDetails(String departmentId,
                                                  String policyDuration) {
        Object _ret =
            this.riInvokeExportedMethod(this, "getAgingResponseManagementDetails",
                                        new String[] { "java.lang.String",
                                                       "java.lang.String" },
                                        new Object[] { departmentId,
                                                       policyDuration });
        return;
    }


    public void filterByPolicyIdToPreface(String itemid, String userId,
                                          String isInternalExternal) {
        Object _ret =
            this.riInvokeExportedMethod(this, "filterByPolicyIdToPreface",
                                        new String[] { "java.lang.String",
                                                       "java.lang.String",
                                                       "java.lang.String" },
                                        new Object[] { itemid, userId,
                                                       isInternalExternal });
        return;
    }


    public void filterPolicyActiveOnlyViewUserIdAndDocumentType(String userId,
                                                                String isInternalExternal,
                                                                String queryType,
                                                                String queryValue) {
        Object _ret =
            this.riInvokeExportedMethod(this,"filterPolicyActiveOnlyViewUserIdAndDocumentType",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {userId, isInternalExternal, queryType, queryValue});
        return;
    }


    public void submitAuditTrail(String usrId, String documentId, String notes,
                                 String actionTaken) {
        Object _ret =
            this.riInvokeExportedMethod(this,"submitAuditTrail",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {usrId, documentId, notes, actionTaken});
        return;
    }

    public void refreshPolicyMaintenance() {
        Object _ret =
            this.riInvokeExportedMethod(this,"refreshPolicyMaintenance",null,null);
        return;
    }

    public void getWhatsNewPolicysUserId(String isInternalExternal,
                                         String userId, String depId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getWhatsNewPolicysUserId",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {isInternalExternal, userId, depId});
        return;
    }

    public void getWhatsNewPolicys(String isInternalExternal, String orgId,
                                   String depId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getWhatsNewPolicys",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {isInternalExternal, orgId, depId});
        return;
    }

    public void getSupportingDocumentsRequests(String departmentId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getSupportingDocumentsRequests",new String [] {"java.lang.String"},new Object[] {departmentId});
        return;
    }

    public void getSupportingDocumentsDecision(String requestId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getSupportingDocumentsDecision",new String [] {"java.lang.String"},new Object[] {requestId});
        return;
    }

    public void getPolicyPublishDecision(String itemid) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getPolicyPublishDecision",new String [] {"java.lang.String"},new Object[] {itemid});
        return;
    }

    public void getInsernalUserFaqManagementDetails(String departmentId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getInsernalUserFaqManagementDetails",new String [] {"java.lang.String"},new Object[] {departmentId});
        return;
    }

    public void getFaqManagementDetails() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getFaqManagementDetails",null,null);
        return;
    }

    public void getEnquiryResponse(String enquiryFAQId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getEnquiryResponse",new String [] {"java.lang.String"},new Object[] {enquiryFAQId});
        return;
    }

    public void getEnquiryManagementDetails(String departmentId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getEnquiryManagementDetails",new String [] {"java.lang.String"},new Object[] {departmentId});
        return;
    }

    public void getApprovalPolicys(String userId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getApprovalPolicys",new String [] {"java.lang.String"},new Object[] {userId});
        return;
    }

    public List<String> getAllSectorsInList() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getAllSectorsInList",null,null);
        return (List<String>)_ret;
    }

    public void getAgingResponseManagementDetails(String departmentId,
                                                  String policyDuration,
                                                  String legislationKey) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getAgingResponseManagementDetails",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {departmentId, policyDuration, legislationKey});
        return;
    }

    public void getAgingReportDetails() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getAgingReportDetails",null,null);
        return;
    }

    public void filterPolicyActiveOnlyViewUserIdAndDocumentType(String userId,
                                                                String isInternalExternal,
                                                                String consultId,
                                                                String openStatus,
                                                                String closeStatus) {
        Object _ret =
            this.riInvokeExportedMethod(this,"filterPolicyActiveOnlyViewUserIdAndDocumentType",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {userId, isInternalExternal, consultId, openStatus, closeStatus});
        return;
    }

    public void filterPolicyActiveOnlyViewUserId(String userId,
                                                 String isInternalExternal) {
        Object _ret =
            this.riInvokeExportedMethod(this,"filterPolicyActiveOnlyViewUserId",new String [] {"java.lang.String","java.lang.String"},new Object[] {userId, isInternalExternal});
        return;
    }

    public void filterPolicyActiveOnlyView(String orgId,
                                           String isInternalExternal) {
        Object _ret =
            this.riInvokeExportedMethod(this,"filterPolicyActiveOnlyView",new String [] {"java.lang.String","java.lang.String"},new Object[] {orgId, isInternalExternal});
        return;
    }

    public void filterCateByParentId() {
        Object _ret =
            this.riInvokeExportedMethod(this,"filterCateByParentId",null,null);
        return;
    }

    public void filterByPolicyIdToPreface(String itemid, String userId,
                                          String isInternalExternal,
                                          String userRoleId, String depOrOrg) {
        Object _ret =
            this.riInvokeExportedMethod(this,"filterByPolicyIdToPreface",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {itemid, userId, isInternalExternal, userRoleId, depOrOrg});
        return;
    }

    public String filterByPolicyIdOnlyPolicyTable(String itemid) {
        Object _ret =
            this.riInvokeExportedMethod(this,"filterByPolicyIdOnlyPolicyTable",new String [] {"java.lang.String"},new Object[] {itemid});
        return (String)_ret;
    }

    public void filterByPolicyId(String itemid, String userId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"filterByPolicyId",new String [] {"java.lang.String","java.lang.String"},new Object[] {itemid, userId});
        return;
    }

    public void createNewPolicy(String policy, String userId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createNewPolicy",new String [] {"java.lang.String","java.lang.String"},new Object[] {policy, userId});
        return;
    }

    public String callFuncPolicyAttachment(String policyId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"callFuncPolicyAttachment",new String [] {"java.lang.String"},new Object[] {policyId});
        return (String)_ret;
    }
}
